### ISSUE TITLE
Zero loss and nan grad_norm when Flash Attention is enabled

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [axolotl-ai-cloud/axolotl#1706]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I expect similar loss and grad_norm when training a model with the same setting regardless whether flash attention is enabled or not.

### Current behaviour

Currently, during training steps (right from the start), I can see messages of
`{'loss': 0.0, 'grad_norm': nan, 'learning_rate': 6.545084971874738e-06, 'epoch': 0.4}`
for few steps, before a 
```
  File "/home/huada524/ondemand/data/sys/myjobs/projects/default/1/huada524-prune-env/lib/python3.10/site-packages/flash_attn/bert_padding.py", line 110, in unpad_input
    indices = torch.nonzero(attention_mask.flatten(), as_tuple=False).flatten()
RuntimeError: CUDA error: an illegal memory access was encountered
```
error appear and the training stops.

However, if flash attention is disabled with `flash_attention: false`, then the network trains normally.
`{'loss': 3.0972, 'grad_norm': 0.76171875, 'learning_rate': 3.4549150281252635e-06, 'epoch': 0.6}`

### Steps to reproduce

1. I Installed my axolotl on a remote cluster with 3x L40 graphic cards with slurm, using the following script:
```
module load python
module load cuda

echo "Setting up python venv..."
python -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip
pip install -U wheel
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124 -I
pip install ninja
export TORCH_CUDA_ARCH_LIST="8.6;8.9"
export CUDA_VISIBLE_DEVICES=2
export LD_LIBRARY_PATH=/home/huada524/ondemand/data/sys/myjobs/projects/default/1/venv/lib64/python3.10/site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH
pip install -v -U "git+https://github.com/facebookresearch/xformers.git@main#egg=xformers"

cd axolotl
git pull
pip install packaging
pip install -e '.[flash-attn,deepspeed]'
# I manually disabled xformers installation from axolotl/requirements.txt so it won't attempt to override the one I just compiled with.
# I also have to apply this patch https://github.com/microsoft/DeepSpeed/issues/5603 to make sure axolotl would launch
cd ..
```
2. I started the training using the script below:
```
module load python
module load cuda

source venv/bin/activate

export CUDA_VISIBLE_DEVICES=2

export WANDB_API_KEY=xxxxxxx
export LD_LIBRARY_PATH=/home/huada524/ondemand/data/sys/myjobs/projects/default/1/venv/lib64/python3.10/site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH

accelerate launch -m axolotl.cli.train config_llama3_40B_dora.yaml
```
Note the model I am training the lora with is meta's llama-3-70B model with some of its layers removed.
GPU are running on a CUDA version of 12.5, while the loaded module is 12.3.
****************************************
**** Axolotl Dependency Versions *****
  accelerate: 0.30.1         
        peft: 0.11.1         
transformers: 4.41.1         
         trl: 0.8.7.dev0     
       torch: 2.4.0.dev20240610+cu124
bitsandbytes: 0.43.1         
****************************************

### Config yaml

```yaml
base_model: /home/huada524/ondemand/data/sys/myjobs/projects/default/1/PruneMe/slice_with_mergekit/merged
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

pretraining_dataset:
  - path: HuggingFaceFW/fineweb-edu
    name: default
    type: completion
val_set_size: 0.05
max_steps: 10
output_dir: ./outputs/out

adapter: qlora
lora_r: 8
lora_alpha: 4
lora_dropout: 0.0
lora_target_linear: true
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj
#  - lm_head
peft_use_dora: false
lora_model_dir:

sequence_len: 1024
sample_packing: true
pad_to_sequence_len: true

wandb_mode: online
wandb_project: Creating Llama-3-40B
wandb_entity:
wandb_watch:
wandb_name: Experimental_Runs

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 1e-5
#loraplus_lr_embedding: 1e-6

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: false

warmup_steps: 0
evals_per_epoch: 1
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
#  - full_shard
#  - auto_wrap
fsdp_config:
#  fsdp_limit_all_gathers: true
#  fsdp_sync_module_states: true
#  fsdp_offload_params: true
#  fsdp_use_orig_params: false
#  fsdp_cpu_ram_efficient_loading: true
#  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
#  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
#  fsdp_state_dict_type: FULL_STATE_DICT
#  fsdp_sharding_strategy: FULL_SHARD
special_tokens:
  pad_token: <|end_of_text|>
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

5783839c6e29bb148041338772040c85aaae4646

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by bofei5675** [comment]
Get same error

**Comment by saucam** [comment]
I think I get the same error

```
[rank22]:   File "/opt/conda/lib/python3.11/site-packages/flash_attn/bert_padding.py", line 212, in pad_input
[rank22]:     output = index_put_first_axis(hidden_states, indices, batch * seqlen)
[rank22]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank22]:   File "/opt/conda/lib/python3.11/site-packages/torch/autograd/function.py", line 598, in apply
[rank22]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank22]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank22]:   File "/opt/conda/lib/python3.11/site-packages/flash_attn/bert_padding.py", line 51, in forward
[rank22]:     output[indices] = values
[rank22]:     ~~~~~~^^^^^^^^^
[rank22]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank22]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank22]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank22]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f39d2711897 in /opt/conda/lib/python3.11/site-packages/torch/lib/libc10.so)
```

**Comment by Kaminoatowo** [comment]
I think I have a similar issue, but in my case loss was set to 0.0 and grad_norm was set to 1.0.

I am running a qlora adapter fine-tuning with flash attention enabled and zero1 configs.

`{'loss': 1.1688, 'grad_norm': 1.0166690349578857, 'learning_rate': 0.00013633776091081593, 'epoch': 0.14}
{'loss': 1.1058, 'grad_norm': 0.788006067276001, 'learning_rate': 0.0001391840607210626, 'epoch': 0.14}
{'loss': 2.4984, 'grad_norm': 1.0, 'learning_rate': 0.00014203036053130928, 'epoch': 0.14}
{'loss': 0.0, 'grad_norm': 1.0, 'learning_rate': 0.00014487666034155596, 'epoch': 0.15}
{'loss': 0.0, 'grad_norm': 1.0, 'learning_rate': 0.00014772296015180266, 'epoch': 0.15}
{'loss': 0.0, 'grad_norm': 1.0, 'learning_rate': 0.00015056925996204934, 'epoch': 0.15} `

This issue doesn't stop the training. In fact the problem happens at epoch 0.15 of 3.0 and continues until the end. When I try to infere from the trained model I couldn't obtain anything as a response.

I'll paste some other parts of the configuration file.

```adapter: qlora

chat_template: gemma3
eot_tokens:
  - <end_of_turn>
datasets:
  - path: /path/to/custom/data.jsonl
    type: chat_template
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
  - path: path/to/hf/data
    type: alpaca_chat.load_qa
  - path: path/to/other/hf/data
    type:
      field_instruction: query
      field_output: response

load_in_4bit: true

ddp_find_unused_parameters: true

gradient_accumulation_steps: 4          # Increased to balance memory for two datasets
micro_batch_size: 2                     # Smaller micro-batch to fit longer sequences and 2 datasets
num_epochs: 3                          # Increased for more training
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0003                   # Slightly lower to stabilize combined training

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 10                      # Increased to reduce log noise
flash_attention: true                   # Enable flash attention if supported
eager_attention:                       # Disable eager since flash is on


# LoRA options (keep your setup)
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: 'model.language_model.layers.[\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj'

warmup_ratio: 0.1
evals_per_epoch: 2                    # More frequent evals due to longer training
saves_per_epoch: 2
weight_decay: 0.0

bf16: true
fp16:                            # Disable fp16 to avoid mixed precision conflict with bf16
tf32: true

**Comment by NanoCode012** [comment]
@Kaminoatowo , can you try without `deepspeed: `? Just with DDP?

**Comment by maymosido** [comment]
I get the same error. I am using the most recent version of Axolotl. 
When I set `sample_packing: false`, the error disappears and it trains as expected but the number of steps necessary jumps from 5K to 55K and it takes much longer to train.

**Comment by NanoCode012** [comment]
> I get the same error. I am using the most recent version of Axolotl. When I set `sample_packing: false`, the error disappears and it trains as expected but the number of steps necessary jumps from 5K to 55K and it takes much longer to train.

@maymosido I think we need more details than this. Configs , env setup, logs. This thread is also old and contains several other issues. Would recommend making new one.

**Comment by ved1beta** [comment]
i think this issue is resolved , tested with config bellow closing ! 
``` 
base_model: unsloth/Llama-3.2-1B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer
load_in_4bit: true
strict: false
datasets:
  - path: /workspace/axolotl/repro_text.jsonl
    type: completion
    field: text
val_set_size: 0.0
max_steps: 10
output_dir: ./outputs/repro_cd_on
adapter: qlora
lora_r: 8
lora_alpha: 4
lora_dropout: 0.0
lora_target_linear: true
lora_target_modules: [gate_proj, down_proj, up_proj, q_proj, v_proj, k_proj, o_proj]
sequence_len: 1024
sample_packing: true
pad_to_sequence_len: true
gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 1e-5
train_on_inputs: false
bf16: true
tf32: false
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1
flash_attention: true
warmup_steps: 0
weight_decay: 0.0
dataset_processes: 4
special_tokens:
  pad_token: <|end_of_text|>

````
