### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by rodriheck** [axolotl-ai-cloud/axolotl#217]
I am using a dataset of the format 'completion' to finetune a Falcon model. All json files are stored inside a folder named 'corpus' with the following format:

`{'text': ...}
`

 The yml looks like this:
```
datasets:
  - path: corpus
    type: "completion"
```

But I am getting this error:

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/user/miniconda3/envs/fastai/lib/libcudart.so'), PosixPath('/home/user/miniconda3/envs/fastai/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/user/miniconda3/envs/fastai/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
WARNING:root:`trust_remote_code` is set to true. Please make sure that you reviewed the remote code/model.
INFO:root:loading tokenizer... tiiuae/falcon-7b
Using bos_token, but it is not set yet.
Using pad_token, but it is not set yet.
Using unk_token, but it is not set yet.
INFO:root:Unable to find prepared dataset in last_run_prepared/adaed1483e102f8f139bc363237dab29
INFO:root:Loading raw datasets...
INFO:root:No seed provided, using default seed of 42
Resolving data files: 100%|██████████████| 4585/4585 [00:00<00:00, 14958.87it/s]
Traceback (most recent call last):
  File "/home/user/axolotl/scripts/finetune.py", line 352, in <module>
    fire.Fire(train)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/axolotl/scripts/finetune.py", line 222, in train
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 385, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 106, in load_tokenized_prepared_datasets
    ds = load_dataset(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/load.py", line 1773, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/load.py", line 1502, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/load.py", line 1137, in dataset_module_factory
    ).get_module()
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/load.py", line 712, in get_module
    data_files = DataFilesDict.from_local_or_remote(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/data_files.py", line 779, in from_local_or_remote
    DataFilesList.from_local_or_remote(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/data_files.py", line 747, in from_local_or_remote
    data_files = resolve_patterns_locally_or_by_urls(base_path, patterns, allowed_extensions)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/data_files.py", line 347, in resolve_patterns_locally_or_by_urls
    for path in _resolve_single_pattern_locally(base_path, pattern, allowed_extensions):
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/datasets/data_files.py", line 291, in _resolve_single_pattern_locally
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/home/user/axolotl/corpus' at /home/user/axolotl
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/fastai/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/miniconda3/envs/fastai/bin/python', 'scripts/finetune.py', 'config.yml']' returned non-zero exit status 1.
```

Which seems weird since it was able to load the files. Why wouldn't it be able to find the corpus folder?

Any ideas of what I am doing wrong?

**Comment by NanoCode012** [comment]
Unfortunately, I don't think we support loading by folder yet. You would need to point to each individual file or combine them into one. I'm very sorry for that .. We're open to PR this, if you're interested.

**Comment by rodriheck** [comment]
Oh, I see! What's weird is that even if I change the yml file to

```
datasets:
  - path: corpus
    data_files:
      - text0.json
    type: "completion"
```

I still get the same error, aka: 
`FileNotFoundError: Unable to find '/home/user/axolotl/corpus' at /home/user/axolotl
`

**Comment by NanoCode012** [comment]
You might want 
```yaml
- path: corpus/text0.json
```

Although, I might recommend converting the json to jsonl (there is script in the data directory) and then combine all those files.

**Comment by rodriheck** [comment]
Thanks for the suggestion. I did that but now the following message appears:

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/user/miniconda3/envs/fastai/lib/libcudart.so.11.0'), PosixPath('/home/user/miniconda3/envs/fastai/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/user/miniconda3/envs/fastai/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
WARNING:root:`trust_remote_code` is set to true. Please make sure that you reviewed the remote code/model.
INFO:root:loading tokenizer... tiiuae/falcon-7b
Using bos_token, but it is not set yet.
Using pad_token, but it is not set yet.
Using unk_token, but it is not set yet.
INFO:root:Unable to find prepared dataset in last_run_prepared/43194b0cd77ed92a1e04ae3ec307e7fc
INFO:root:Loading raw datasets...
INFO:root:No seed provided, using default seed of 42
WARNING:datasets.builder:Found cached dataset json (/home/user/.cache/huggingface/datasets/json/default-bd0b29b61691cfff/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 875.82it/s]
INFO:root:tokenizing, merging, and shuffling master dataset
Traceback (most recent call last):
  File "/home/user/axolotl/scripts/finetune.py", line 352, in <module>
    fire.Fire(train)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/axolotl/scripts/finetune.py", line 222, in train
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 385, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 256, in load_tokenized_prepared_datasets
    samples = samples + list(d)
  File "/home/user/axolotl/src/axolotl/datasets.py", line 40, in __iter__
    yield self.prompt_tokenizer.tokenize_prompt(example)
  File "/home/user/axolotl/src/axolotl/prompt_tokenizers.py", line 233, in tokenize_prompt
    tokenized_full_prompt = self._tokenize(full_prompt)
  File "/home/user/axolotl/src/axolotl/prompt_tokenizers.py", line 70, in _tokenize
    result["input_ids"][-1] != self.tokenizer.eos_token_id
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/fastai/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/miniconda3/envs/fastai/bin/python', 'scripts/finetune.py', 'config.yml']' returned non-zero exit status 1.
```

**Comment by rodriheck** [comment]
Thanks for the suggestion. I did that but now I am facing the following message:

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/user/miniconda3/envs/fastai/lib/libcudart.so'), PosixPath('/home/user/miniconda3/envs/fastai/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/user/miniconda3/envs/fastai/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
WARNING:root:`trust_remote_code` is set to true. Please make sure that you reviewed the remote code/model.
INFO:root:loading tokenizer... tiiuae/falcon-7b
Using bos_token, but it is not set yet.
Using pad_token, but it is not set yet.
Using unk_token, but it is not set yet.
INFO:root:Unable to find prepared dataset in last_run_prepared/43194b0cd77ed92a1e04ae3ec307e7fc
INFO:root:Loading raw datasets...
INFO:root:No seed provided, using default seed of 42
Downloading and preparing dataset json/default to /home/user/.cache/huggingface/datasets/json/default-bd0b29b61691cfff/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4...
Downloading data files: 100%|██████████████████| 1/1 [00:00<00:00, 12985.46it/s]
Extracting data files: 100%|████████████████████| 1/1 [00:00<00:00, 1874.97it/s]
Dataset json downloaded and prepared to /home/user/.cache/huggingface/datasets/json/default-bd0b29b61691cfff/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4. Subsequent calls will reuse this data.
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 567.72it/s]
INFO:root:tokenizing, merging, and shuffling master dataset
Traceback (most recent call last):
  File "/home/user/axolotl/scripts/finetune.py", line 352, in <module>
    fire.Fire(train)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/axolotl/scripts/finetune.py", line 222, in train
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 385, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 256, in load_tokenized_prepared_datasets
    samples = samples + list(d)
  File "/home/user/axolotl/src/axolotl/datasets.py", line 40, in __iter__
    yield self.prompt_tokenizer.tokenize_prompt(example)
  File "/home/user/axolotl/src/axolotl/prompt_tokenizers.py", line 233, in tokenize_prompt
    tokenized_full_prompt = self._tokenize(full_prompt)
  File "/home/user/axolotl/src/axolotl/prompt_tokenizers.py", line 70, in _tokenize
    result["input_ids"][-1] != self.tokenizer.eos_token_id
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/fastai/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/home/user/miniconda3/envs/fastai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/miniconda3/envs/fastai/bin/python', 'scripts/finetune.py', 'config.yml']' returned non-zero exit status 1.
```

EDIT: sorry, I double checked and there were some empty strings that were causing the error. Now everything works! Thanks for the helpful responses.

**Comment by enn-nafnlaus** [comment]
Okay, I've been struggling with this exact same issue (if you don't support loading by folder, please put a check in, don't just close this issue as done!  :)  ).  Merging .json together into a single json array and specifying an absolute path to that array is a valid workaround. But again, we need a check and a useful error message, otherwise people will keep wasting hours or days on this  :)

**Comment by NanoCode012** [comment]
@enn-nafnlaus , hey, a PR for this just merged. Please let us know how it works. 

https://github.com/OpenAccess-AI-Collective/axolotl/pull/221
