### ISSUE TITLE
"CUDA error: invalid argument" with FSDP + QLora finetuning

### ISSUE THREAD

**Issue by peterwilli** [axolotl-ai-cloud/axolotl#2409]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Training should work and continue after running `axolotl train`

### Current behaviour

I got a server with 3x RTX 4000 ADA on Runpod.io to try out FSDP. I end up with this error, no matter how much I try:

```
(axolotl) ➜  /workspace tail -f nohup.out
[2025-03-12 22:05:32,869] [DEBUG] [axolotl.load_tokenizer:300] [PID:20494] [RANK:1] PAD: 128001 / <|end_of_text|>
[2025-03-12 22:05:32,870] [DEBUG] [axolotl.load_tokenizer:301] [PID:20494] [RANK:1] UNK: None / None
[2025-03-12 22:05:32,870] [INFO] [axolotl.load_tokenizer:315] [PID:20494] [RANK:1] No Chat template selected. Consider adding a chat template for easier inference.
[2025-03-12 22:05:33,008] [DEBUG] [axolotl.load_tokenizer:298] [PID:20493] [RANK:0] EOS: 128001 / <|end_of_text|>
[2025-03-12 22:05:33,009] [DEBUG] [axolotl.load_tokenizer:299] [PID:20493] [RANK:0] BOS: 128000 / <|begin_of_text|>
[2025-03-12 22:05:33,009] [DEBUG] [axolotl.load_tokenizer:300] [PID:20493] [RANK:0] PAD: 128001 / <|end_of_text|>
[2025-03-12 22:05:33,010] [DEBUG] [axolotl.load_tokenizer:301] [PID:20493] [RANK:0] UNK: None / None
[2025-03-12 22:05:33,010] [INFO] [axolotl.load_tokenizer:315] [PID:20493] [RANK:0] No Chat template selected. Consider adding a chat template for easier inference.
[2025-03-12 22:05:33,010] [DEBUG] [axolotl.train.train:82] [PID:20493] [RANK:0] loading model and peft_config...
Loading checkpoint shards: 100%|██████████| 30/30 [11:20<00:00, 22.68s/it]

Loading checkpoint shards: 100%|██████████| 30/30 [11:20<00:00, 22.68s/it]
[2025-03-12 22:16:54,343] [INFO] [axolotl.load_lora:1311] [PID:20495] [RANK:2] found linear modules: ['down_proj', 'gate_proj', 'k_proj', 'o_proj', 'q_proj', 'up_proj', 'v_proj']
[2025-03-12 22:16:54,378] [INFO] [axolotl.load_lora:1311] [PID:20494] [RANK:1] found linear modules: ['down_proj', 'gate_proj', 'k_proj', 'o_proj', 'q_proj', 'up_proj', 'v_proj']
[2025-03-12 22:16:54,578] [INFO] [axolotl.load_lora:1311] [PID:20493] [RANK:0] found linear modules: ['down_proj', 'gate_proj', 'k_proj', 'o_proj', 'q_proj', 'up_proj', 'v_proj']
[2025-03-12 22:16:57,903] [INFO] [axolotl.load_model:1182] [PID:20495] [RANK:2] cuda memory usage after adapters: 0.000GB ()
[2025-03-12 22:16:57,953] [INFO] [axolotl.load_model:1182] [PID:20494] [RANK:1] cuda memory usage after adapters: 0.000GB ()
When using FSDP full shard, instead of using `gradient_checkpointing` in TrainingArguments, please use `activation_checkpointing` in `fsdp_config`. The former introduces a redundant AllGather operation in backward pass. Reference: https://github.com/huggingface/transformers/issues/30404
/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/core/trainers/base.py:177: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `AxolotlTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*_args, **kwargs)
When using FSDP full shard, instead of using `gradient_checkpointing` in TrainingArguments, please use `activation_checkpointing` in `fsdp_config`. The former introduces a redundant AllGather operation in backward pass. Reference: https://github.com/huggingface/transformers/issues/30404
/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/core/trainers/base.py:177: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `AxolotlTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*_args, **kwargs)
trainable params: 414,187,520 || all params: 70,967,894,016 || trainable%: 0.5836
[2025-03-12 22:17:00,872] [INFO] [axolotl.load_model:1182] [PID:20493] [RANK:0] cuda memory usage after adapters: 0.000GB ()
When using FSDP full shard, instead of using `gradient_checkpointing` in TrainingArguments, please use `activation_checkpointing` in `fsdp_config`. The former introduces a redundant AllGather operation in backward pass. Reference: https://github.com/huggingface/transformers/issues/30404
/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/core/trainers/base.py:177: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `AxolotlTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*_args, **kwargs)
[2025-03-12 22:17:01,742] [INFO] [axolotl.train.train:134] [PID:20493] [RANK:0] Pre-saving adapter config to ./outputs/out/qlora-llama3-70b
[2025-03-12 22:17:02,114] [INFO] [axolotl.train.train:173] [PID:20493] [RANK:0] Starting trainer...
[2025-03-12 22:17:02,756] [INFO] [axolotl.utils.samplers.multipack.calc_min_len:203] [PID:20493] [RANK:0] gather_len_batches: [1259, 1259, 1259]
  0%|          | 0/836 [00:00<?, ?it/s]You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/train.py", line 113, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/train.py", line 87, in do_cli
[rank0]:     return do_train(parsed_cfg, parsed_cli_args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/train.py", line 44, in do_train
[rank0]:     model, tokenizer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/train.py", line 188, in train
[rank0]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2171, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2530, in _inner_training_loop
[rank0]:     with context():
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 983, in no_sync
[rank0]:     with context():
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1055, in no_sync
[rank0]:     _lazy_init(self, self)
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 140, in _lazy_init
[rank0]:     _share_state_and_init_handle_attrs(state, root_module)
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 226, in _share_state_and_init_handle_attrs
[rank0]:     handle.init_flat_param_attributes()
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 1232, in init_flat_param_attributes
[rank0]:     flat_param._local_shard = flat_param._local_shard.pin_memory(
[rank0]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank1]: Traceback (most recent call last):
[rank1]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank1]:   File "<frozen runpy>", line 88, in _run_code
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/train.py", line 113, in <module>
[rank1]:     fire.Fire(do_cli)
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/train.py", line 87, in do_cli
[rank1]:     return do_train(parsed_cfg, parsed_cli_args)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/train.py", line 44, in do_train
[rank1]:     model, tokenizer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank1]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/train.py", line 188, in train
[rank1]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2171, in train
[rank1]:     return inner_training_loop(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2530, in _inner_training_loop
[rank1]:     with context():
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank1]:     return next(self.gen)
[rank1]:            ^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 983, in no_sync
[rank1]:     with context():
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank1]:     return next(self.gen)
[rank1]:            ^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1055, in no_sync
[rank1]:     _lazy_init(self, self)
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 140, in _lazy_init
[rank1]:     _share_state_and_init_handle_attrs(state, root_module)
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 226, in _share_state_and_init_handle_attrs
[rank1]:     handle.init_flat_param_attributes()
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 1232, in init_flat_param_attributes
[rank1]:     flat_param._local_shard = flat_param._local_shard.pin_memory(
[rank1]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: CUDA error: invalid argument
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  0%|          | 0/836 [01:24<?, ?it/s]
[rank0]:[W312 22:19:10.576566156 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0312 22:19:42.985000 20363 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 20495 closing signal SIGTERM
E0312 22:20:07.251000 20363 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 20493) of binary: /root/miniconda3/envs/axolotl/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/axolotl/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1163, in launch_command
    multi_gpu_launcher(args)
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 792, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.train FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-12_22:19:42
  host      : 2617a5f23acf
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 20494)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-12_22:19:42
  host      : 2617a5f23acf
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 20493)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
[2025-03-12 22:20:07,939] [ERROR] [root.train:171] [PID:20231] Failed to train/fine-tune config '70b.yml': Command '['accelerate', 'launch', '-m', 'axolotl.cli.train', '70b.yml', '--debug-num-examples', '0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/root/miniconda3/envs/axolotl/bin/axolotl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/main.py", line 322, in main
    cli()
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/utils.py", line 62, in wrapper
    return func(*args, **filtered_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/main.py", line 173, in train
    raise exc
  File "/root/miniconda3/envs/axolotl/lib/python3.11/site-packages/axolotl/cli/main.py", line 158, in train
    subprocess.run(cmd, check=True)  # nosec B603
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/axolotl/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['accelerate', 'launch', '-m', 'axolotl.cli.train', '70b.yml', '--debug-num-examples', '0']' returned non-zero exit status 1.
```

### Steps to reproduce

- Get a 3x RTX 4000 ADA on runpod.io
- Install Axolotl
- Copy paste the example config
- run `axolotl train <config name>`

### Config yaml

```yaml
# optionally might have model_type or tokenizer_type
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer  # PreTrainedTokenizerFast
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/out/qlora-llama3-70b

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 0.00001

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
special_tokens:
  pad_token: <|end_of_text|>
```

### Possible solution

I tried running `export CUDA_VISIBLE_DEVICES='0,1,2'` before starting the training, but this doesn't work sadly.
Also, the training was hanging completely, unless I run `export NCCL_P2P_LEVEL=PIX` beforehand, which now brings me to where I am now and I kinda ran out of ideas

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

Python 3.11.11

### axolotl branch-commit

0.7.0 from pypi

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, on off chance, have you tried with 2 (or even number) of GPUs?

**Comment by nicoboss** [comment]
I have the same issue on latest master using 2x RTX 4090 on my local setup
Setting `fsdp_offload_params: false` fixes the issue but makes me run out of memory.

Config:
```yaml
base_model: /bpool/OpenThinker2-32B

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: Guilherme34/uncensor
    type: chat_template
    chat_template: qwen_25
    field_messages: messages
    message_field_role: role
    message_field_content: content
    roles:
      system:
        - system
      user:
        - user
      assistant:
        - assistant
dataset_prepared_path: last_run_prepared
val_set_size: 0.0
output_dir: ./outputs/out/OpenThinker2-32B-Uncensored
save_safetensors: true

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true

adapter: qlora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 4
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
logging_steps: 1
flash_attention: true

warmup_steps: 10
evals_per_epoch: 1
eval_table_size: 20
eval_max_new_tokens: 128
saves_per_epoch: 1
save_total_limit: 20
debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen2DecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
special_tokens:
```

Relevant part of logs:
```
[2025-04-29 17:43:24,056] [INFO] [axolotl.train.execute_training:213] [PID:14680] [RANK:0] Starting trainer...
  0%|                                                                                                                               | 0/1872 [00:00<?, ?it/s]You're using a Qwen2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
You're using a Qwen2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
[rank1]: Traceback (most recent call last):
[rank1]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank1]:   File "<frozen runpy>", line 88, in _run_code
[rank1]:   File "/apool/axolotl/src/axolotl/cli/train.py", line 121, in <module>
[rank1]:     fire.Fire(do_cli)
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/src/axolotl/cli/train.py", line 95, in do_cli
[rank1]:     return do_train(parsed_cfg, parsed_cli_args)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/src/axolotl/cli/train.py", line 51, in do_train
[rank1]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/src/axolotl/train.py", line 529, in train
[rank1]:     execute_training(cfg, trainer, resume_from_checkpoint)
[rank1]:   File "/apool/axolotl/src/axolotl/train.py", line 215, in execute_training
[rank1]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
[rank1]:     return inner_training_loop(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank1]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/transformers/trainer.py", line 3736, in training_step
[rank1]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/src/axolotl/core/trainers/base.py", line 374, in compute_loss
[rank1]:     loss = super().compute_loss(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/transformers/trainer.py", line 3801, in compute_loss
[rank1]:     outputs = model(**inputs)
[rank1]:               ^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/accelerate/utils/operations.py", line 814, in forward
[rank1]:     return model_forward(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/accelerate/utils/operations.py", line 802, in __call__
[rank1]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank1]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 840, in forward
[rank1]:     args, kwargs = _root_pre_forward(self, self, args, kwargs)
[rank1]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 517, in _root_pre_forward
[rank1]:     _lazy_init(state, module)
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 140, in _lazy_init
[rank1]:     _share_state_and_init_handle_attrs(state, root_module)
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 180, in _share_state_and_init_handle_attrs
[rank1]:     handle.init_flat_param_attributes()
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/apool/axolotl/venv/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 1221, in init_flat_param_attributes
[rank1]:     flat_param._local_shard = flat_param._local_shard.pin_memory()
[rank1]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: CUDA error: invalid argument
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by nicoboss** [comment]
This is so strange. I spent the past few hours playing around with different configurations and found multiple similar ones that worked and now that I retested above posted one it now suddenly works as well. I have not changed anything on my axolotl installation and also have not rebooted the server. The GPU is only used for Compute and not any kind of display or any other application so no idea how this issue magically fixed itself. I was consistently able to reproduce this issue before and now it works every time. Maybe some caching left over from other configurations somehow made this work. Well I am just be happy it works. In case anyone wonders with above configuration I get 19.767 GiB out of 23.988GiB on each 4090 GPU so it wasn't anywhere close on running out of memory.

**Comment by nicoboss** [comment]
After successfully training 1 epoch I paused axolotl and used the GPUs for some llama.cpp imatrix computation for a while. Big mistake because now when I try to resume training using the same exact configurations this issue occurs again every single time. I have not changed anything. This issue really just randomly occurs sometimes and if it does it seems to be consistent as I already tried running it many times and it always resulted in this error.

**Comment by NanoCode012** [comment]
Thanks for sharing your experience. Please let us know if you manage to narrow down the cause as I'm quite confused too.

By resume training, do you mean `resume_checkpoint: ` or starting a new one?

**Comment by nicoboss** [comment]
> Thanks for sharing your experience. Please let us know if you manage to narrow down the cause as I'm quite confused too.

I will do. It is really hard for me to pinpoint this issue as it is so random.

> By resume training, do you mean `resume_checkpoint: ` or starting a new one?

I in tried booth and got the error booth while trying to resume training using `auto_resume_from_checkpoints: true` and when trying to start fresh. I only trained for like an hour so I wouldn't mind starting fresh.

**Comment by nicoboss** [comment]
While researching this issue I noticed that other finetuning frameworks like LLaMA-Factory experience the same issue so this is likely not an issue of axelotl but some 3rd party dependency: https://github.com/hiyouga/LLaMA-Factory/issues/5617. I'm on axolotl master with latest stable PyTorch v2.7.0 with CUDA 12.6 and NVidia driver 555.42.02

**Comment by nicoboss** [comment]
After even more research it seems likely that this is an issue of PyTorch or GPU drivers as I found reports of it occurring for persons that directly work with PyTorch without any finetuning framework: https://widedeepspace.net/2023/03/12/1191/ - you probably need to use a translator to understand but in that "Updated on March 1st, 2025" box they state that they are now experience this exact issue using the code they posted on this blog in March 2023.

**Comment by NanoCode012** [comment]
@nicoboss , thanks for looking into this. Just to clarify, the blog didn't have an attached solution, correct?

**Comment by nicoboss** [comment]
> [@nicoboss](https://github.com/nicoboss) , thanks for looking into this. Just to clarify, the blog didn't have an attached solution, correct?

Yes that is correct. The attached blog article only states that their code no longer works with GPU offloading as of 1st of March 2025 due to this exact error. They also mention that they tried downgrading PyTorch, GPU Drivers and CUDA toolkit without any success and that the model they try to load should not cause them to run out of GPU memory.

**Comment by nicoboss** [comment]
I think I just found a reliable workaround for this issue. All one has to do is to completely power of the server wait a few seconds and then power it on again. Then one should run `nvidia-smi` to initialize the GPUs and then run axolotl without running any application using the GPU before that. This seam to always fix this issue for me. I have no idea what causes this but seems like a GPU driver issue. My GPU driver is almost 1 year old so maybe that is why I'm experiencing this. Just PCIe reseting the GPUs is not enough to fix the issue.

**Comment by nicoboss** [comment]
I now upgraded to NVidia driver 575.51.03 which is the latest beta driver available, CUDA 12.9.0_575.51.03 and PyTorch 2.7.0+cu128 and I'm still often encountering this issue when the GPU was before used for imatrix training. I can also confirm that the only thing that matters to reproduce it seems to be FSDP parameter offloading with multiple GPUs. It is not related to QLora at all and also occurs when training a lora in 16-bit precision. Turning the server off and back on always reliable fixes the issue and it does not occur again as long axolotl is all I run.

Here my confic that also sometimes results in this issue:
```yaml
base_model: /dpool/gemma-3-27b-it

load_in_8bit: false
load_in_4bit: false
strict: false

# gemma3 doesn't seem to play nice with ddp
ddp_find_unused_parameters: true

datasets:
  - path: /apool/axolotl/train_dataset.jsonl
    ds_type: json
    split: train
    field: text
    type: completion

dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./outputs/out

adapter: lora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules: '(?:.*?(?:language|text).*?(?:self_attn|attention|attn|mlp|feed_forward|ffn|dense).*?(?:k_proj|v_proj|q_proj|out_proj|fc1|fc2|o_proj|gate_proj|up_proj|down_proj).*?)|(?:\\bmodel\\.layers\\.[\\d]{1,}\\.(?:self_attn|attention|attn|mlp|feed_forward|ffn|dense)\\.(?:(?:k_proj|v_proj|q_proj|out_proj|fc1|fc2|o_proj|gate_proj|up_proj|down_proj)))'

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 0.00005

bf16: true
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
auto_resume_from_checkpoints: true
logging_steps: 1
flash_attention: true
eager_attention: false

warmup_steps: 10
evals_per_epoch: 40
eval_max_new_tokens: 128
saves_per_epoch: 40
save_total_limit: 100

debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Gemma3DecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
special_tokens:
```

**Comment by NanoCode012** [comment]
That's an interesting find. Unfortunately, I'm not sure how we could repro this to look into it 😕 

Are you running bare metal or from our docker image?

**Comment by nicoboss** [comment]
> That's an interesting find. Unfortunately, I'm not sure how we could repro this to look into it 😕

Unfortunately I have no idea as well. I can't really reproduce it myself in any reliable way. It seems in some way related to what the GPU was used before running axolotl which is so strange as it shouldn’t matter. For the next time this issue occurs I wrote a CUDA application to fill my entire GPU global memory and GPU shared memory with zeros just to check if maybe something isn't getting cleaned properly. Please let me know if there is anything I can do to help figuring out what is causing this.

> Are you running bare metal or from our docker image?

 I install axolotl using the "Edge/Development Build" method described under https://docs.axolotl.ai/docs/installation.html. I'm around every 2 weeks performing a full axolotl reinstall by recreating the entire venv always updating to latest master. I'm running axolotl inside an LXC container on Proxmox VE. The GPUs are directly passed to the LXC container by giving it access to `/dev/nvidia0`, `/dev/nvidia`, `/dev/nvidiactl`, `/dev/nvidia-uvm` and `/dev/nvidia-uvm-tools`. I don't think it's an issue with my specific setup or installation but I will try to run axolotl directly on the host the next time I experience this issue just to make sure and maybe even try to run the official docker image.

**Comment by Nero10578** [comment]
Just wanted to add that I am also getting the same exact issue and the fix was also shutting down my server and starting from a cold boot. Seems to be a driver issue? It is pretty weird and seems to only started happening recently. Makes me think its something with ubuntu recently since I didn't upgrade drivers for a long time.

Edit: Now actually I can't get axolotl to run with FSDP and offload anymore...opened a new issue that shows my problem. https://github.com/axolotl-ai-cloud/axolotl/issues/2743
