### ISSUE TITLE
fsdp_offload_params cause "RuntimeError: CUDA error: invalid argument" error but no offload works

### ISSUE THREAD

**Issue by Nero10578** [axolotl-ai-cloud/axolotl#2743]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I did not change drivers, and FSDP offload used to work for me about 2 weeks back with my last successful train with it enabled on May 22 on the latest commit of 21 May. I then merely updated to the latest axolotl commit and did the install command again a few times to try out the newer models and features, but now FSDP offload isn't working.

I tried reverting to the older commit where I had a train successfully complete using FSDP offload and it makes no difference. The same error persists. I even reinstalled my ubuntu OS and properly installed the nvidia driver, cuda toolkit and the axolotl environment and its the same result. Is this caused by some dependency somewhere that doesn't revert back with going to an older axolotl commit? It severely limits the sequence length I can train.

The example I show below I am running on 6xRTX3090Ti but I tried going back to 4 only just in case it needs to be powers of two and it makes no difference.

### Current behaviour

```
[2025-05-30 23:22:46,673] [INFO] [axolotl.utils.callbacks.on_train_begin:819] [PID:74892] [RANK:0] The Axolotl config has been saved to the WandB run under files.
  0%|                                                                                                                                                                                                             | 0/270 [00:00<?, ?it/s]You're using a Qwen2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
[rank1]: Traceback (most recent call last):
[rank1]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank1]:   File "<frozen runpy>", line 88, in _run_code
[rank1]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 121, in <module>
[rank1]:     fire.Fire(do_cli)
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 95, in do_cli
[rank1]:     return do_train(parsed_cfg, parsed_cli_args)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 51, in do_train
[rank1]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/axolotl/src/axolotl/train.py", line 571, in train
[rank1]:     execute_training(cfg, trainer, resume_from_checkpoint)
[rank1]:   File "/home/arli/axolotl/src/axolotl/train.py", line 221, in execute_training
[rank1]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
[rank1]:     return inner_training_loop(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2559, in _inner_training_loop
[rank1]:     with context():
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank1]:     return next(self.gen)
[rank1]:            ^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 1055, in no_sync
[rank1]:     with context():
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank1]:     return next(self.gen)
[rank1]:            ^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1055, in no_sync
[rank1]:     _lazy_init(self, self)
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 140, in _lazy_init
[rank1]:     _share_state_and_init_handle_attrs(state, root_module)
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 226, in _share_state_and_init_handle_attrs
[rank1]:     handle.init_flat_param_attributes()
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 1232, in init_flat_param_attributes
[rank1]:     flat_param._local_shard = flat_param._local_shard.pin_memory(
[rank1]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: CUDA error: invalid argument
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank2]: Traceback (most recent call last):
[rank2]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank2]:   File "<frozen runpy>", line 88, in _run_code
[rank2]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 121, in <module>
[rank2]:     fire.Fire(do_cli)
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank2]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank2]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank2]:     component, remaining_args = _CallAndUpdateTrace(
[rank2]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank2]:     component = fn(*varargs, **kwargs)
[rank2]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 95, in do_cli
[rank2]:     return do_train(parsed_cfg, parsed_cli_args)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 51, in do_train
[rank2]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank2]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/axolotl/src/axolotl/train.py", line 571, in train
[rank2]:     execute_training(cfg, trainer, resume_from_checkpoint)
[rank2]:   File "/home/arli/axolotl/src/axolotl/train.py", line 221, in execute_training
[rank2]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
[rank2]:     return inner_training_loop(
[rank2]:            ^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2559, in _inner_training_loop
[rank2]:     with context():
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank2]:     return next(self.gen)
[rank2]:            ^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 1055, in no_sync
[rank2]:     with context():
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank2]:     return next(self.gen)
[rank2]:            ^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1055, in no_sync
[rank2]:     _lazy_init(self, self)
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 140, in _lazy_init
[rank2]:     _share_state_and_init_handle_attrs(state, root_module)
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 226, in _share_state_and_init_handle_attrs
[rank2]:     handle.init_flat_param_attributes()
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank2]:     return func(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 1239, in init_flat_param_attributes
[rank2]:     ).pin_memory(device=self.device)
[rank2]:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: RuntimeError: CUDA error: invalid argument
[rank2]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank2]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank2]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/arli/axolotl/src/axolotl/cli/train.py", line 121, in <module>
    fire.Fire(do_cli)
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arli/axolotl/src/axolotl/cli/train.py", line 95, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arli/axolotl/src/axolotl/cli/train.py", line 51, in do_train
    model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arli/axolotl/src/axolotl/train.py", line 571, in train
    execute_training(cfg, trainer, resume_from_checkpoint)
  File "/home/arli/axolotl/src/axolotl/train.py", line 221, in execute_training
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2559, in _inner_training_loop
    with context():
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 1055, in no_sync
    with context():
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1055, in no_sync
    _lazy_init(self, self)
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 140, in _lazy_init
    _share_state_and_init_handle_attrs(state, root_module)
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 180, in _share_state_and_init_handle_attrs
    handle.init_flat_param_attributes()
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 1239, in init_flat_param_attributes
    ).pin_memory(device=self.device)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 121, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 95, in do_cli
[rank0]:     return do_train(parsed_cfg, parsed_cli_args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/axolotl/src/axolotl/cli/train.py", line 51, in do_train
[rank0]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/axolotl/src/axolotl/train.py", line 571, in train
[rank0]:     execute_training(cfg, trainer, resume_from_checkpoint)
[rank0]:   File "/home/arli/axolotl/src/axolotl/train.py", line 221, in execute_training
[rank0]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2245, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2559, in _inner_training_loop
[rank0]:     with context():
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 1055, in no_sync
[rank0]:     with context():
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/contextlib.py", line 137, in __enter__
[rank0]:     return next(self.gen)
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1055, in no_sync
[rank0]:     _lazy_init(self, self)
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 140, in _lazy_init
[rank0]:     _share_state_and_init_handle_attrs(state, root_module)
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 180, in _share_state_and_init_handle_attrs
[rank0]:     handle.init_flat_param_attributes()
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/arli/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 1239, in init_flat_param_attributes
[rank0]:     ).pin_memory(device=self.device)
[rank0]:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

W0530 23:22:51.028000 74691 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 74892 closing signal SIGTERM
W0530 23:22:51.029000 74691 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 74894 closing signal SIGTERM
W0530 23:22:51.029000 74691 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 74895 closing signal SIGTERM
W0530 23:22:51.030000 74691 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 74896 closing signal SIGTERM
W0530 23:22:51.030000 74691 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 74897 closing signal SIGTERM
```

### Steps to reproduce

Run a QLoRA 4-bit train with FSDP1 with offload enabled. It will cause the above error.

### Config yaml

```yaml
base_model: /home/arli/models/QwQ-32B

train_on_inputs: false
group_by_length: false
load_in_8bit: 
load_in_4bit: true
strict: false
sequence_len: 8192
bf16: auto
tf32: false
flash_attention: true

shuffle_merged_datasets: true

#lora_on_cpu: true
#gpu_memory_limit: 21GiB

datasets:
  - path: /home/arli/datasets/RpR-v4/conversations-QwQ-derep-deimp.jsonl
    type: input_output

dataset_prepared_path: ./lora_last_run_prepared

# Iterations
num_epochs: 1
saves_per_epoch: 8
saves_total_limit: 8

# Evaluation
val_set_size: 0.0025
eval_max_new_tokens: 128
eval_sample_packing: false
evals_per_epoch: 8
eval_table_size:

# LoRA
output_dir: ./qlora_out_RpR_v5
adapter: qlora
lora_model_dir:
lora_r: 128
lora_alpha: 128
lora_dropout: 0
lora_target_linear: true
peft_use_rslora: true
save_safetensors: true
#loraplus_lr_ratio: 8

# Sampling
sample_packing: true
pad_to_sequence_len: true

# Batching
gradient_accumulation_steps: 10
micro_batch_size: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# Optimizer
optimizer: adamw_torch_fused
lr_scheduler: rex
learning_rate: 1e-5
warmup_ratio: 0.1

# Misc
auto_resume_from_checkpoints: true
logging_steps: 1
weight_decay: 0

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
cut_cross_entropy: true
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
#liger_fused_linear_cross_entropy: true

unsloth_cross_entropy_loss: true
unsloth_rms_norm: true

# Multi-GPU
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen2DecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_activation_checkpointing: false
```

### Environment

```
PyTorch version: 2.6.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.2 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: version 4.0.2
Libc version: glibc-2.39

Python version: 3.11.11 (main, Dec 11 2024, 16:28:39) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.11.0-26-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090 Ti
GPU 1: NVIDIA GeForce RTX 3090 Ti
GPU 2: NVIDIA GeForce RTX 3090 Ti
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090 Ti
GPU 5: NVIDIA GeForce RTX 3090 Ti

Nvidia driver version: 565.57.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               96
On-line CPU(s) list:                  0-95
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 7R13 48-Core Processor
CPU family:                           25
Model:                                1
Thread(s) per core:                   2
Core(s) per socket:                   48
Socket(s):                            1
Stepping:                             1
Frequency boost:                      enabled
CPU(s) scaling MHz:                   60%
CPU max MHz:                          2650.0000
CPU min MHz:                          1500.0000
BogoMIPS:                             5300.15
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
Virtualization:                       AMD-V
L1d cache:                            1.5 MiB (48 instances)
L1i cache:                            1.5 MiB (48 instances)
L2 cache:                             24 MiB (48 instances)
L3 cache:                             192 MiB (6 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-95
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==2.0.1
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] torch==2.6.0+cu124
[pip3] torchao==0.10.0
[pip3] torchaudio==2.6.0+cu124
[pip3] torchvision==0.21.0+cu124
[pip3] transformers==4.51.3
[pip3] triton==3.2.0
[conda] nccl                        2.21.5.1             ha515578_0
[conda] numpy                       2.0.1                pypi_0           pypi
[conda] nvidia-nccl-cu12            2.21.5               pypi_0           pypi
[conda] torch                       2.6.0+cu124          pypi_0           pypi
[conda] torchao                     0.10.0               pypi_0           pypi
[conda] torchaudio                  2.6.0+cu124          pypi_0           pypi
[conda] torchvision                 0.21.0+cu124         pypi_0           pypi
[conda] transformers                4.51.3               pypi_0           pypi
[conda] triton                      3.2.0                pypi_0           pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
Aphrodite Version: N/A
Aphrodite Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NODE    NODE    NODE    NODE    NODE    0-95    0               N/A
GPU1    NODE     X      NODE    NODE    NODE    NODE    0-95    0               N/A
GPU2    NODE    NODE     X      PHB     NODE    NODE    0-95    0               N/A
GPU3    NODE    NODE    PHB      X      NODE    NODE    0-95    0               N/A
GPU4    NODE    NODE    NODE    NODE     X      PHB     0-95    0               N/A
GPU5    NODE    NODE    NODE    NODE    PHB      X      0-95    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Possible solution

_No response_

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/6778856804e2c6d5f9903006916f9cd4bfb27756

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
This configuration worked for me for qwen3 https://wandb.ai/axolotl-ai/qwen3-fsdp2/runs/5q42c9z5/files/tmp/axolotl_config_dvln14d4.yml
You don't need the unsloth optimizations since liger does the same optimizations and has better multi-gpu support.
