### ISSUE TITLE
Getting `AttributeError: 'Gemma3ForConditionalGeneration' object has no attribute 'vocab_size` when using CCE

### ISSUE THREAD

**Issue by sanchit-ahuja** [axolotl-ai-cloud/axolotl#2874]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Training begins

### Current behaviour

I have 4 L4 GPUs with 24GB of VRAM on the same node. I am trying to use CCE because without that I am getting OOM on using deepspeed in zero1. However, I am getting this error:
My transformers version is 4.52.3 and I have installed the CCE upstream for axolotl
`AttributeError: 'Gemma3ForConditionalGeneration' object has no attribute 'vocab_size'`

### Steps to reproduce

I am sharing the config file, if we run it, we observe this error for a Gemma Fine-tuned model.

### Config yaml

```yaml
# A list of one or more datasets to finetune the model with
base_model: sarvamai/sarvam-translate

plugins:
- axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin

strict: true
chat_template: gemma3
datasets:
- path: /home/random/sanchit/data/train/train_en_to_kn_samples.jsonl
  type: chat_template
  field_messages: messages
  message_property_mappings:
    role: role
    content: value
- path: /home/random/sanchit/data/train/train_kn_to_en_samples.jsonl
  type: chat_template
  field_messages: messages
  message_property_mappings:
    role: role
    content: value


device: cuda
# Seed for reproducibility
seed: 42

bf16: true
dataset_processes: 45
val_set_size: 0.02
sequence_len: 8192
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true
# Whether to use gradient checkpointing. Available options are: true, false, 'offload',
# 'offload_disk'.
# https://huggingface.co/docs/transformers/v4.18.0/en/performance#gradient-checkpointing
gradient_checkpointing: true

# The maximum length of an input to train with, this should typically be less than 2048
# as most models have a token/context limit of 2048

# Whether to use flash attention patch https://github.com/Dao-AILab/flash-attention
flash_attention: true

# How much of the dataset to set aside as evaluation. 1 = 100%, 0.50 = 50%, etc. 0 for
# no eval.
# val_set_size: 0.02


# Add or change special tokens. If you add tokens here, you don't need to add them to
# the `tokens` list.
eot_tokens:
  - <end_of_turn>

train_on_inputs: false
# Maximum number of iterations to train for. It precedes num_epochs which means that if
# both are set, num_epochs will not be guaranteed. e.g., when 1 epoch is 1000 steps =>
# `num_epochs: 2` and `max_steps: 100` will train for 100 steps
# --- Core training settings ---
num_epochs: 1
gradient_accumulation_steps: 2
micro_batch_size: 1
# --- Warmup settings ---
warmup_ratio: 0.03  # 3% of total steps (~low dataset, faster convergence)

# --- Evaluation settings ---
eval_strategy: steps  

# --- Saving settings ---
save_strategy: epoch
saves_per_epoch: 5

# --- Logging ---
logging_steps: 50  # Log every 50 steps


# --- Save format ---
save_safetensors: True

# --- Logging tools ---
use_tensorboard: true
# low_cpu_mem_usage: true
wandb_project: "translation-en-kn-ift"
wandb_entity: "translation-adalat-ai"
wandb_name: "lora_linear_run_l4"

# --- Adapter & LoRA settings ---
adapter: lora
lora_r: 16
lora_alpha: 32
lora_target_linear: true

# --- Learning rate & batch size ---
learning_rate: 0.0002
weight_decay: 0.01

# --- Optimizer & scheduler ---
optimizer: adamw_torch_fused
lr_scheduler: linear

# --- Output & Hub settings ---
output_dir: "./model-out/exp1"
dataset_prepared_path: last_run_prepared
trust_remote_code: True
# deepspeed: deepspeed_configs/zero3_bf16_cpuoffload_all.json
deepspeed: deepspeed_configs/zero1.json
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/5a961ec

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Do you have more trace please? I feel like we've fixed this before.

**Comment by sanchit-ahuja** [comment]
Here you go:

```[rank0]:   File "/home/random/sanchit/axolotl_train/.venv/lib/python3.11/site-packages/axolotl/integrations/cut_cross_entropy/monkeypatch/gemma3.py", line 240, in 
cce_forward_multimodal                                                                                                                                             
[rank0]:     if input_ids is not None and self.config.image_token_index >= self.vocab_size:                                                                        
[rank0]:                                                                   ^^^^^^^^^^^^^^^                                                                         
[rank0]:   File "/home/random/sanchit/axolotl_train/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1940, in __getattr__                      
[rank0]:     raise AttributeError(                                                                                                                                 
[rank0]: AttributeError: 'Gemma3ForConditionalGeneration' object has no attribute 'vocab_size'```

**Comment by NanoCode012** [comment]
Hey! I think you would need to reinstall the correct version. That's an older version :) https://docs.axolotl.ai/docs/custom_integrations.html#installation

**Comment by sanchit-ahuja** [comment]
This is the one I installed. Let me re-install.

**Comment by sanchit-ahuja** [comment]
I am getting in the same error @NanoCode012

**Comment by sanchit-ahuja** [comment]
Also, while using the LigerPlugin:

```[rank0]:   File "/home/random/sanchit/axolotl_train/.venv/lib/python3.11/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func      
[rank0]:     return func(*args, **kwargs)                                                                                                                 
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
[rank0]:   File "/home/random/sanchit/axolotl_train/.venv/lib/python3.11/site-packages/liger_kernel/transformers/model/gemma3.py", line 205, in multimodal
_forward                                                                                                                                                  
[rank0]:     if input_ids is not None and self.config.image_token_index >= self.vocab_size:                                                               
[rank0]:                                                                   ^^^^^^^^^^^^^^^                                                                
[rank0]:   File "/home/random/sanchit/axolotl_train/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1940, in __getattr__             
[rank0]:     raise AttributeError(                                                                                                                        
[rank0]: AttributeError: 'Gemma3ForConditionalGeneration' object has no attribute 'vocab_size'                                                            
  0%|                                                                                             ```

**Comment by NanoCode012** [comment]
Could you please make sure you uninstall the previous one first before installing the current?

You can see that the line does not exist anymore in main https://github.com/axolotl-ai-cloud/ml-cross-entropy/blob/622068a5291794415b01c004754f26464e6ce7f7/cut_cross_entropy/transformers/gemma3.py#L1

> LigerPlugin

We currently don't patch the liger kernels ourselves (yet). If you want to use liger, you'll need to install from source as it just got fixed 10h ago there https://github.com/linkedin/Liger-Kernel/pull/787

**Comment by sanchit-ahuja** [comment]
I did. I am using `uv` to manage installations. Let me retry again.

Let me look into Liger fix as well.

**Comment by NanoCode012** [comment]
Does it now work?

**Comment by sanchit-ahuja** [comment]
Yep, it works! Thanks. Closing this issue.
