### ISSUE TITLE
ModuleNotFoundError: No module named 'axolotl.monkeypatch.models' when using latest Axolotl with Gemma-3

### ISSUE THREAD

**Issue by iljung1106** [axolotl-ai-cloud/axolotl#3008]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Fine-tuning a Gemma-3–based model using the latest Axolotl main branch should start training normally—loading the model, applying PEFT adapters, and proceeding through epochs—without any import or CUDA errors.

### Current behaviour

Current Behavior

Training immediately fails during dataset saving with:

ModuleNotFoundError: No module named 'axolotl.monkeypatch.models'  
If you manually place modeling.py and __init__.py from the Gemma-3 code into axolotl/monkeypatch/models/..., the import error disappears but you then hit:

### Steps to reproduce

Steps to Reproduce

1.Clone the latest Axolotl main branch.

2.Create a config file gemma27b_lora.yaml targeting google/gemma-3-27b-it (see below).

3.Run:axolotl train gemma27b_lora.yaml

4.Observe the ModuleNotFoundError in the logs as training begins.

### Config yaml

```yaml
base_model: google/gemma-3-27b-it
load_in_4bit: true

ddp_find_unused_parameters: false

chat_template: chatml
datasets:
  - path: ./train_simple.jsonl
    type: chat_template
    field_messages: messages

sequence_len: 16384
tokenizer_use_fast: true

adapter: qlora
lora_r: 128
lora_alpha: 256
lora_dropout: 0.05
lora_target_modules: "model.language_model.layers.[\\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj"

bf16: true
device_map: "auto"
skip_memory_warmup: true

micro_batch_size: 1
gradient_accumulation_steps: 16

learning_rate: 4e-4
num_train_epochs: 1

wandb_project: gemma27b
output_dir: ./gemma27b_lora

push_to_hub: true
hub_model_id: ij/gemma3-27b-lora-bigdata5

deepspeed: ./zero3_bf16.json
```

### Possible solution

Ensure the Axolotl patch manager can actually import the Gemma-3 monkeypatch files by creating the missing package structure under axolotl/monkeypatch/models/gemma3/

I tried it and got this error

RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable  

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.14

### axolotl branch-commit

5639552064c838d4cf3016570b30cba182962d49

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Can you paste the full stack trace please? I'll take a look shortly

**Comment by iljung1106** [comment]
#@@ #@@      @@# @@#
    @@  @@          @@  @@           =@@#                               @@                 #@    =@@#.
    @@    #@@@@@@@@@    @@           #@#@=                              @@                 #@     .=@@
      #@@@@@@@@@@@@@@@@@            =@# @#     ##=     ##    =####=+    @@      =#####+  =#@@###.   @@
    @@@@@@@@@@/  +@@/  +@@          #@  =@=     #@=   @@   =@#+  +#@#   @@    =@#+  +#@#   #@.      @@
    @@@@@@@@@@  ##@@  ##@@         =@#   @#      =@# @#    @@      @@   @@    @@      #@   #@       @@
     @@@@@@@@@@@@@@@@@@@@          #@=+++#@=      =@@#     @@      @@   @@    @@      #@   #@       @@
                                  =@#=====@@     =@# @#    @@      @@   @@    @@      #@   #@       @@
    @@@@@@@@@@@@@@@@  @@@@        #@      #@=   #@=  +@@   #@#    =@#   @@.   =@#    =@#   #@.      @@
                                 =@#       @#  #@=     #@   =#@@@@#=    +#@@=  +#@@@@#=    .##@@+   @@
    @@@@  @@@@@@@@@@@@@@@@

ipex flag is deprecated, will be removed in Accelerate v1.10. From 2.7.0, PyTorch has all needed optimizations for Intel CPU and XPU.
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `3`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2025-08-02 18:50:21,495] [INFO] [axolotl.utils.config.log_gpu_memory_usage:107] [PID:4176] [RANK:0] cuda memory usage baseline: 0.000GB (+0.753GB misc)
[2025-08-02 18:50:21,496] [INFO] [axolotl.cli.config.load_cfg:244] [PID:4176] [RANK:0] config:
{
  "adapter": "qlora",
  "axolotl_config_path": "/workspace/gemma27b_lora.yaml",
  "base_model": "google/gemma-3-27b-it",
  "base_model_config": "google/gemma-3-27b-it",
  "batch_size": 48,
  "bf16": true,
  "capabilities": {
    "bf16": true,
    "compute_capability": "sm_80",
    "fp8": false,
    "n_gpu": 3,
    "n_node": 1
  },
  "chat_template": "chatml",
  "dataloader_num_workers": 3,
  "dataloader_pin_memory": true,
  "dataloader_prefetch_factor": 256,
  "dataset_processes": 32,
  "datasets": [
    {
      "chat_template": "tokenizer_default",
      "field_messages": "messages",
      "message_property_mappings": {
        "content": "content",
        "role": "role"
      },
      "path": "./train_simple.jsonl",
      "trust_remote_code": false,
      "type": "chat_template"
    }
  ],
  "ddp": true,
  "ddp_find_unused_parameters": false,
  "device": "cuda:0",
  "device_map": {
    "": 0
  },
  "env_capabilities": {
    "torch_version": "2.6.0"
  },
  "eval_batch_size": 1,
  "eval_causal_lm_metrics": [
    "sacrebleu",
    "comet",
    "ter",
    "chrf"
  ],
  "eval_max_new_tokens": 128,
  "eval_table_size": 0,
  "fp16": false,
  "gradient_accumulation_steps": 16,
  "gradient_checkpointing": false,
  "hub_model_id": "ij/gemma3-27b-webnovel-lora-bigdata5",
  "is_multimodal": true,
  "learning_rate": 0.0004,
  "lisa_layers_attribute": "model.layers",
  "load_best_model_at_end": false,
  "load_in_4bit": true,
  "load_in_8bit": false,
  "local_rank": 0,
  "lora_alpha": 256,
  "lora_dropout": 0.05,
  "lora_r": 128,
  "lora_target_modules": "model.language_model.layers.[\\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj",
  "loraplus_lr_embedding": 1e-06,
  "lr_scheduler": "cosine",
  "max_prompt_len": 512,
  "mean_resizing_embeddings": false,
  "micro_batch_size": 1,
  "model_config_type": "gemma3",
  "num_epochs": 1.0,
  "optimizer": "adamw_torch_fused",
  "output_dir": "./gemma27b_webnovel_lora",
  "pretrain_multipack_attn": true,
  "pretrain_multipack_buffer_size": 10000,
  "processor_config": "google/gemma-3-27b-it",
  "qlora_sharded_model_loading": false,
  "ray_num_workers": 1,
  "resources_per_worker": {
    "GPU": 1
  },
  "sample_packing_bin_size": 200,
  "sample_packing_group_size": 100000,
  "save_only_model": false,
  "save_safetensors": true,
  "sequence_len": 16384,
  "sequence_parallel_degree": 1,
  "shuffle_merged_datasets": true,
  "skip_prepare_dataset": false,
  "strict": false,
  "tokenizer_config": "google/gemma-3-27b-it",
  "tokenizer_use_fast": true,
  "torch_dtype": "torch.bfloat16",
  "train_on_inputs": false,
  "trl": {
    "log_completions": false,
    "mask_truncated_completions": false,
    "ref_model_mixup_alpha": 0.9,
    "ref_model_sync_steps": 64,
    "scale_rewards": true,
    "sync_ref_model": false,
    "use_vllm": false,
    "vllm_server_host": "0.0.0.0",
    "vllm_server_port": 8000
  },
  "use_ray": false,
  "use_wandb": true,
  "val_set_size": 0.0,
  "vllm": {
    "device": "auto",
    "dtype": "auto",
    "gpu_memory_utilization": 0.9,
    "host": "0.0.0.0",
    "port": 8000
  },
  "wandb_project": "gemma27b_webnovel",
  "weight_decay": 0.0,
  "world_size": 3
}
[2025-08-02 18:50:22,781] [INFO] [axolotl.utils.data.shared.load_preprocessed_dataset:467] [PID:4176] [RANK:0] Unable to find prepared dataset in last_run_prepared/0a5f6c9e428b99ccaab15865d970ab72
[2025-08-02 18:50:22,782] [INFO] [axolotl.utils.data.sft._load_raw_datasets:310] [PID:4176] [RANK:0] Loading raw datasets...
[2025-08-02 18:50:22,782] [WARNING] [axolotl.utils.data.sft._load_raw_datasets:312] [PID:4176] [RANK:0] Processing datasets during training can lead to VRAM instability. Please pre-process your dataset using `axolotl preprocess path/to/config.yml`.
Generating train split: 119902 examples [00:08, 13456.53 examples/s]
[2025-08-02 18:50:31,803] [INFO] [axolotl.utils.data.wrappers.get_dataset_wrapper:88] [PID:4176] [RANK:0] Loading dataset: ./train_simple.jsonl with base_type: chat_template and prompt_style: None
[2025-08-02 18:50:31,819] [INFO] [axolotl.prompt_strategies.chat_template.__call__:930] [PID:4176] [RANK:0] Using chat template:
---
{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '
' + message['content'] + '<|im_end|>' + '
'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
' }}{% endif %}

---
[2025-08-02 18:50:31,828] [WARNING] [axolotl.prompt_strategies.chat_template._validate_eot_and_eos_tokens:320] [PID:4176] [RANK:0] EOS token '<eos>' not found in chat_template. Please check if your template/EOS token is correct.
Tokenizing Prompts (num_proc=32): 100%|█| 119902/119902 [01:21<00:00, 1479.93 ex
[2025-08-02 18:51:56,007] [INFO] [axolotl.utils.data.utils.drop_long_seq_in_dataset:180] [PID:4176] [RANK:0] min_input_len: 313
[2025-08-02 18:51:56,008] [INFO] [axolotl.utils.data.utils.drop_long_seq_in_dataset:182] [PID:4176] [RANK:0] max_input_len: 11069
Dropping Long Sequences (>16384) (num_proc=32): 100%|█| 119902/119902 [00:07<00:
Saving the dataset (19/19 shards): 100%|█| 119902/119902 [00:06<00:00, 17987.87 
[2025-08-02 18:52:10,635] [INFO] [axolotl.utils.data.shared.load_preprocessed_dataset:467] [PID:4178] [RANK:2] Unable to find prepared dataset in last_run_prepared/0a5f6c9e428b99ccaab15865d970ab72
[2025-08-02 18:52:10,635] [INFO] [axolotl.utils.data.sft._load_raw_datasets:310] [PID:4178] [RANK:2] Loading raw datasets...
[2025-08-02 18:52:10,765] [INFO] [axolotl.utils.data.wrappers.get_dataset_wrapper:88] [PID:4178] [RANK:2] Loading dataset: ./train_simple.jsonl with base_type: chat_template and prompt_style: None
Dropping Long Sequences (>16384) (num_proc=32):  52%|▌| 62000/119902 [00:03<00:0[2025-08-02 18:52:17,997] [INFO] [axolotl.utils.data.sft._prepare_standard_dataset:123] [PID:4176] [RANK:0] Maximum number of steps set at 2498
processor_config.json: 100%|██████████████████| 70.0/70.0 [00:00<00:00, 732kB/s]
chat_template.json: 100%|██████████████████| 1.61k/1.61k [00:00<00:00, 11.6MB/s]
preprocessor_config.json: 100%|████████████████| 570/570 [00:00<00:00, 3.74MB/s]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Dropping Long Sequences (>16384) (num_proc=32): 100%|█| 119902/119902 [00:07<00:
Saving the dataset (0/19 shards):   0%|       | 0/119902 [00:00<?, ? examples/s]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/axolotl/cli/train.py", line 119, in <module>
    fire.Fire(do_cli)
  File "/usr/local/lib/python3.11/dist-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/cli/train.py", line 93, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/cli/train.py", line 49, in do_train
    model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/train.py", line 558, in train
    ) = setup_model_and_trainer(cfg, dataset_meta)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/train.py", line 506, in setup_model_and_trainer
    model, tokenizer, peft_config, processor = setup_model_and_tokenizer(cfg)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/train.py", line 86, in setup_model_and_tokenizer
    model, peft_config = model_loader.load()
                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/loaders/model.py", line 155, in load
    self.patch_manager.apply_pre_model_load_patches()
  File "/usr/local/lib/python3.11/dist-packages/axolotl/loaders/patch_manager.py", line 67, in apply_pre_model_load_patches
    self._apply_gemma3_conditional_generation_forward_patch()
  File "/usr/local/lib/python3.11/dist-packages/axolotl/loaders/patch_manager.py", line 244, in _apply_gemma3_conditional_generation_forward_patch
    from axolotl.monkeypatch.models.gemma3.modeling import (
ModuleNotFoundError: No module named 'axolotl.monkeypatch.models'
Saving the dataset (0/19 shards):   1%| | 1000/119902 [00:06<13:18, 148.88 exampW0802 18:52:28.442000 4043 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 4177 closing signal SIGTERM
W0802 18:52:28.443000 4043 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 4178 closing signal SIGTERM
E0802 18:52:28.771000 4043 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 4176) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/usr/local/lib/python3.11/dist-packages/accelerate/commands/launch.py", line 1190, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.11/dist-packages/accelerate/commands/launch.py", line 815, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.11/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.11/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-02_18:52:28
  host      : c2a102789100
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4176)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
[2025-08-02 18:52:29,314] [ERROR] [axolotl.cli.main.train:184] [PID:3891] [RANK:0] Failed to train/fine-tune config '/workspace/gemma27b_lora.yaml': Command '['accelerate', 'launch', '-m', 'axolotl.cli.train', '/workspace/gemma27b_lora.yaml', '--debug-num-examples', '0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/bin/axolotl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/cli/main.py", line 364, in main
    cli()
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/cli/utils.py", line 65, in wrapper
    return func(*args, **filtered_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/axolotl/cli/main.py", line 186, in train
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/axolotl/cli/main.py", line 171, in train
    subprocess.run(cmd, check=True)  # nosec B603
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['accelerate', 'launch', '-m', 'axolotl.cli.train', '/workspace/gemma27b_lora.yaml', '--debug-num-examples', '0']' returned non-zero exit status 1.

**Comment by timofey** [comment]
@iljung1106 try reinstalling from the latest `main`. I had exact same issue on 0.11 tag. Reinstalled from `main` and it works without problems.

**Comment by winglian** [comment]
I agree that you may be on an old branch as `_apply_gemma3_conditional_generation_forward_patch` doesn't exist in the current codebase on `main`

**Comment by iljung1106** [comment]
Sorry. I accidently installed two different version of axolotl. It was my mistake.
