### ISSUE TITLE
BUG:cpu_ram_efficient_loading: TRUE falis with FSDP2

### ISSUE THREAD

**Issue by ved1beta** [axolotl-ai-cloud/axolotl#3476]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

cpu_ram effi runs fine with fsdp 2 

### Current behaviour

AttributeError: e_score_correction_bias is not an nn.Parameter` due to modeling source
```
sharding_strategy is deprecated in favor of reshard_after_forward. This will be removed in a future version of Accelerate.                                                           [105/904]
[2026-03-07 04:58:42,954] [INFO] [axolotl.train] Pre-saving adapter config to ./outputs/glm4.7-flash-qlora-fsdp-out...                                                                        
[2026-03-07 04:58:42,968] [INFO] [axolotl.train] Pre-saving tokenizer to ./outputs/glm4.7-flash-qlora-fsdp-out...                                                                             
[2026-03-07 04:58:43,336] [INFO] [axolotl.train] Pre-saving model config to ./outputs/glm4.7-flash-qlora-fsdp-out...                                                                          
[2026-03-07 04:58:43,363] [INFO] [axolotl.train] Starting trainer...                                                                                                                          
 the tokeizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with[100/904$
nizer's values. Updated tokens: {'bos_token_id': None}.                                                                                                                                       
        -07 04:59:08,428] [INFO] [axolotl.utils.samplers.multipack] gather_len_batches: [61, 61]                                                                                      [98/904]
[2026-03-07 04:59:17,769] [INFO] [axolotl.monkeypatch.accelerate.fsdp2] Broadcasting full state dict to all ranks...                                                                          
[rank0]:[E307 05:29:18.767469871 ProcessGroupNCCL.cpp:683] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=17, OpType=SCATTER, NumelIn=573440, NumelOut=1146880, Timeou
        00000) ran for 1800032 milliseconds before timing out.                                                                                                                        [95/904]
: 17, la[E307 05:29:18.768073729 ProcessGroupNCCL.cpp:2241] [PG ID 0 PG GUID 0(default_pg) Rank 0]  failure detected by watchdog at work sequence id: 17 PG status: last enqueued work[94/904$
        eted work: 16                                                                                                                                                                 [93/904]
g TORCH_[E307 05:29:18.768109338 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by settin[92/904$
        CE_BUFFER_SIZE to a non-zero value.                                                                                                                                           [91/904]
        [E307 05:29:18.768195925 ProcessGroupNCCL.cpp:2573] [PG ID 0 PG GUID 0(default_pg) Rank 0] First PG on this rank to signal dumping.                                           [90/904]
[rank1]:[E307 05:29:18.803542245 ProcessGroupNCCL.cpp:683] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=13, OpType=SCATTER, NumelIn=384, NumelOut=0, Timeout(ms)=180
        n for 1800085 milliseconds before timing out.                                                                                                                                 [88/904]
: 855, l[E307 05:29:18.803703487 ProcessGroupNCCL.cpp:2241] [PG ID 0 PG GUID 0(default_pg) Rank 1]  failure detected by watchdog at work sequence id: 13 PG status: last enqueued work[87/904$
        leted work: 12                                                                                                                                                                [86/904]
g TORCH_[E307 05:29:18.803737494 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by settin[85/904$
        CE_BUFFER_SIZE to a non-zero value.                                                                                                                                           [84/904]
        [E307 05:29:18.803823153 ProcessGroupNCCL.cpp:2573] [PG ID 0 PG GUID 0(default_pg) Rank 1] First PG on this rank to signal dumping.                                           [83/904]
[rank0]:[E307 05:29:18.099127134 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 0] Received a dump signal due to a collective timeout from this local rank and we will try our
anks, th dump the debug info. Last enqueued NCCL work: 17, last completed NCCL work: 16.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across r[81/904$
etwork eof collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as n[80/904$
         bugs in the communications library (e.g. NCCL), etc.                                                                                                                         [79/904]
        [E307 05:29:18.099574742 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 0] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1              [78/904]
[rank1]:[E307 05:29:18.161079108 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 1] Received a dump signal due to a collective timeout from this local rank and we will try our
ranks, t dump the debug info. Last enqueued NCCL work: 855, last completed NCCL work: 12.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across [76/904$
network  of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as [75/904]
        r bugs in the communications library (e.g. NCCL), etc.                                                                                                                        [74/904]
        [E307 05:29:18.161560553 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 1] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1              [73/904]
[rank0]:[E307 05:30:18.278313932 ProcessGroupNCCL.cpp:744] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations m
         on corrupted/incomplete data.                                                                                                                                                [71/904]
        [E307 05:30:18.278360802 ProcessGroupNCCL.cpp:758] [Rank 0] To avoid data inconsistency, we are taking the entire process down.                                               [70/904]
[rank0]:[E307 05:30:18.281097620 ProcessGroupNCCL.cpp:2057] [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collectiv
        ion timeout: WorkNCCL(SeqNum=17, OpType=SCATTER, NumelIn=573440, NumelOut=1146880, Timeout(ms)=1800000) ran for 1800032 milliseconds before timing out.                       [68/904]
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):                                                                 
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x78e7ddb7cb80 in /root/miniconda3/envs/py3.11/lib/p
        1/site-packages/torch/lib/libc10.so)                                                                                                                                          [65/904]
lib/pyth: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x78e79dbb1b67 in /root/miniconda3/envs/py3.11/[64/904$
        ite-packages/torch/lib/libtorch_cuda.so)            
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x78e79dbb6771 in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)               [62/904]
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x78e79dbb79bf in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdf0e6 (0x78e7d64ea0e6 in /root/miniconda3/envs/py3.11/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x78e7debf3ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: clone + 0x44 (0x78e7dec84a04 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=17, OpType=S
CATTER, NumelIn=573440, NumelOut=1146880, Timeout(ms)=1800000) ran for 1800032 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x78e7ddb7cb80 in /root/miniconda3/envs/py3.11/lib/p
ython3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x78e79dbb1b67 in /root/miniconda3/envs/py3.11/lib/pyth
on3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x78e79dbb6771 in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x78e79dbb79bf in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdf0e6 (0x78e7d64ea0e6 in /root/miniconda3/envs/py3.11/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x78e7debf3ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: clone + 0x44 (0x78e7dec84a04 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from run at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2063 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x78e7ddb7cb80 in /root/miniconda3/envs/py3.11/lib/p
ython3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xbef891 (0x78e79db8d891 in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x62d72f (0x78e79d5cb72f in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xdf0e6 (0x78e7d64ea0e6 in /root/miniconda3/envs/py3.11/bin/../lib/libstdc++.so.6)
frame #4: <unknown function> + 0x94ac3 (0x78e7debf3ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #5: clone + 0x44 (0x78e7dec84a04 in /lib/x86_64-linux-gnu/libc.so.6)

[rank1]:[E307 05:30:20.036611330 ProcessGroupNCCL.cpp:744] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations m
ight run on corrupted/incomplete data.
[rank1]:[E307 05:30:20.036665163 ProcessGroupNCCL.cpp:758] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E307 05:30:20.039566920 ProcessGroupNCCL.cpp:2057] [PG ID 0 PG GUID 0(default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collectiv
e operation timeout: WorkNCCL(SeqNum=13, OpType=SCATTER, NumelIn=384, NumelOut=0, Timeout(ms)=1800000) ran for 1800085 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x74ba2617cb80 in /root/miniconda3/envs/py3.11/lib/p
ython3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x74b9e61b1b67 in /root/miniconda3/envs/py3.11/lib/pyth
on3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x74b9e61b6771 in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x74b9e61b79bf in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdf0e6 (0x74ba1eaea0e6 in /root/miniconda3/envs/py3.11/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x74ba271f0ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: clone + 0x44 (0x74ba27281a04 in /lib/x86_64-linux-gnu/libc.so.6)                                                                                                            [19/904]

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=13, OpType=S
CATTER, NumelIn=384, NumelOut=0, Timeout(ms)=1800000) ran for 1800085 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x74ba2617cb80 in /root/miniconda3/envs/py3.11/lib/p
ython3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x74b9e61b1b67 in /root/miniconda3/envs/py3.11/lib/pyth
on3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x74b9e61b6771 in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x74b9e61b79bf in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdf0e6 (0x74ba1eaea0e6 in /root/miniconda3/envs/py3.11/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x74ba271f0ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: clone + 0x44 (0x74ba27281a04 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from run at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2063 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x74ba2617cb80 in /root/miniconda3/envs/py3.11/lib/p
ython3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xbef891 (0x74b9e618d891 in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x62d72f (0x74b9e5bcb72f in /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xdf0e6 (0x74ba1eaea0e6 in /root/miniconda3/envs/py3.11/bin/../lib/libstdc++.so.6)
frame #4: <unknown function> + 0x94ac3 (0x74ba271f0ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #5: clone + 0x44 (0x74ba27281a04 in /lib/x86_64-linux-gnu/libc.so.6)

W0307 05:30:20.519000 6807 site-packages/torch/distributed/elastic/multiprocessing/api.py:908] Sending process 7102 closing signal SIGTERM
E0307 05:30:22.690000 6807 site-packages/torch/distributed/elastic/multiprocessing/api.py:882] failed (exitcode: -6) local_rank: 1 (pid: 7103) of binary: /root/miniconda3/envs/py3.11/bin/pyt
hon3.11
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.11/bin/accelerate", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1396, in launch_command
    multi_gpu_launcher(args)
  File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1023, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/distributed/run.py", line 927, in run
    elastic_launch(
  File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 156, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 293, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
axolotl.cli.train FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2026-03-07_05:30:20
  host      : 271f17292446
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 7103)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 7103
=====================================================
```

### Steps to reproduce

run `/workspace/axolotl/examples/glm47-flash/qlora_fsdp.yaml` with   cpu_ram_efficient_loading: true

### Config yaml

```yaml
NA
```

### Possible solution

NA

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

LTS

### axolotl branch-commit

main 

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Weird, I thought I fixed this bug in the last 1-2 commits of the moe quant PR

**Comment by ved1beta** [comment]
ohh , was able too repro this 3 days ago , willl retest an closee

**Comment by NanoCode012** [comment]
Duplicate #3446
