### ISSUE TITLE
Failures Training gpt-oss-20b

### ISSUE THREAD

**Issue by floaty3** [axolotl-ai-cloud/axolotl#3530]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I would like to train gpt-oss-20b with QLoRA because the LoRA template causes me to get OOM errors on my 32GB VRAM RTX 5090. I expect QLoRA to run. (Plus it would be great if there were a QLoRA example.)

### Current behaviour

I get this error:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for AxolotlConfigWCapabilities
  Value error, Require cfg.load_in_4bit to be True for qlora [type=value_error, input_value={'base_model': '/home/use..._to_sequence_len': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/value_error
```

I would also like to quantize the MoE experts via `quantize_moe_experts`, but that is not compatible with the `lora_target_linear` option. Changing to the `lora_target_experts` option like this

```
#lora_target_linear: true
lora_target_experts: true
```

results in the error

```
Value error, quantize_moe_experts requires load_in_4bit or load_in_8bit [type=value_error, input_value={'base_model': '/home/use..., 'lora_o_kernel': True}, input_type=dict]
```

If I then try setting `load_in_8bit`, that conflicts with the quantization config:

```
Value error, model_quantization_config and load_in_8bit or load_in_4bit cannot be used together. [type=value_error, input_value={'base_model': '/home/use..._to_sequence_len': True}, input_type=dict]
```

### Steps to reproduce

Begin with the LoRA example as a base: https://github.com/axolotl-ai-cloud/axolotl/blob/main/examples/gpt-oss/gpt-oss-20b-sft-lora-singlegpu.yaml

Then just change `lora` to `qlora` and try to preprocess and run.

### Config yaml

```yaml
base_model: openai/gpt-oss-20b
use_kernels: true
model_quantization_config: Mxfp4Config
model_quantization_config_kwargs:
  dequantize: true

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin

experimental_skip_move_to_device: true  # prevent OOM by not putting model to GPU before sharding

datasets:
  - path: HuggingFaceH4/Multilingual-Thinking
    type: chat_template
    field_thinking: thinking
    template_thinking_key: thinking

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./outputs/gpt-oss-out/

sequence_len: 4096
sample_packing: true

adapter: qlora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.0  # dropout not supported when using LoRA over expert parameters
lora_target_linear: true

# TODO: not supported for now, see peft#2710
#lora_target_parameters:  # target the experts in the last two layers
#  - "22._checkpoint_wrapped_module.mlp.experts.gate_up_proj"
#  - "22._checkpoint_wrapped_module.mlp.experts.down_proj"
#  - "23._checkpoint_wrapped_module.mlp.experts.gate_up_proj"
#  - "23._checkpoint_wrapped_module.mlp.experts.down_proj"

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

trackio_project_name:
trackio_run_name:
trackio_space_id:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1

optimizer: adamw_torch_8bit
lr_scheduler: constant_with_warmup
learning_rate: 2e-4

bf16: true
tf32: true

flash_attention: true
attn_implementation: kernels-community/vllm-flash-attn3  # this is not needed if using flash_attn >= 2.8.3

gradient_checkpointing: true
activation_offloading: true

logging_steps: 1
saves_per_epoch: 1
warmup_ratio: 0.1

special_tokens:
eot_tokens:
  - "<|end|>"
```

### Which Operating Systems are you using?

- [x] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.12

### axolotl branch-commit

main/8f19169

### Acknowledgements

- [x] My issue title is concise, descriptive, and in title casing.
- [x] I have searched the existing issues to make sure this bug has not been reported yet.
- [x] I am using the latest version of axolotl.
- [x] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, `lora` on this config is in a way `qlora` already given base weights is in fp4. Per our notes, you'd need more VRAM?
```
# LoRA SFT linear layers (1x48GB @ ~44GiB)
axolotl train examples/gpt-oss/gpt-oss-20b-sft-lora-singlegpu.yaml
```

You would not need quantize_moe_experts I believe. That would be an err on my end

**Comment by floaty3** [comment]
Okay, that makes sense. What is confusing is that `dequantize: true` is specified, and that is where I thought I would be able to get additional VRAM usage reduced somehow, by not dequantizing the model or something during training. I remember training internlm-20b on 24 GB VRAM here a long time ago (no context parallelism), but given the architecture is different, I suppose they do not directly compare.

**Comment by NanoCode012** [comment]
@floaty3 , did you get to retry this with a larger GPU? How did it go?

**Comment by floaty3** [comment]
@NanoCode012 Thank you for checking in. Not yet. I still only have at maximum a 5090 to work with, using 32GB VRAM. I hooked another 24GB card to try with the FSDP full fine tune config from here: https://github.com/axolotl-ai-cloud/axolotl/blob/main/examples/gpt-oss/gpt-oss-20b-fft-fsdp2-offload.yaml (readme says `(2x24GB @ ~21GiB/GPU)`)

Unfortunately, the custom CutCrossEntropyPlugin fails to import HybridCache:

```
[rank0]: ImportError: cannot import name 'HybridCache' from 'transformers.cache_utils' (/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/cache_utils.py)
```

Here is the full log for debugging:
```
[2026-04-03 07:48:13,840] [WARNING] [torchao] Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.8.0+cu128).

     #@@ #@@      @@# @@#
    @@  @@          @@  @@           =@@#                               @@                 #@    =@@#.
    @@    #@@@@@@@@@    @@           #@#@=                              @@                 #@     .=@@
      #@@@@@@@@@@@@@@@@@            =@# @#     ##=     ##    =####=+    @@      =#####+  =#@@###.   @@
    @@@@@@@@@@/  +@@/  +@@          #@  =@=     #@=   @@   =@#+  +#@#   @@    =@#+  +#@#   #@.      @@
    @@@@@@@@@@  ##@@  ##@@         =@#   @#      =@# @#    @@      @@   @@    @@      #@   #@       @@
     @@@@@@@@@@@@@@@@@@@@          #@=+++#@=      =@@#     @@      @@   @@    @@      #@   #@       @@
                                  =@#=====@@     =@# @#    @@      @@   @@    @@      #@   #@       @@
    @@@@@@@@@@@@@@@@  @@@@        #@      #@=   #@=  +@@   #@#    =@#   @@.   =@#    =@#   #@.      @@
                                 =@#       @#  #@=     #@   =#@@@@#=    +#@@=  +#@@@@#=    .##@@+   @@
    @@@@  @@@@@@@@@@@@@@@@

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `2`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2026-04-03 07:48:24,131] [WARNING] [torchao] Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.8.0+cu128).
[2026-04-03 07:48:24,157] [WARNING] [torchao] Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.8.0+cu128).
[2026-04-03 07:48:26,597] [INFO] [axolotl.integrations.base] Attempting to load plugin: axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
[2026-04-03 07:48:27,891] [INFO] [axolotl.integrations.base] Plugin loaded successfully: axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
[2026-04-03 07:48:27,943] [INFO] [axolotl.utils.schemas.validation] explicitly setting `eval_sample_packing` to match `sample_packing`
[2026-04-03 07:48:27,943] [WARNING] [axolotl.utils.schemas.validation] Configuring FSDP fields with the `fsdp_` prefix is deprecated. Please omit the `fsdp_` prefix from the any fields in `fsdp_config`.
[2026-04-03 07:48:28,018] [WARNING] [axolotl.utils.trainer] P2P support not detected, setting `NCCL_P2P_DISABLE=1`
[2026-04-03 07:48:28,025] [INFO] [axolotl.cli.config] config:
{
  "activation_offloading": true,
  "attn_implementation": "kernels-community/vllm-flash-attn3",
  "axolotl_config_path": "examples/gpt-oss/gpt-oss-20b-fft-fsdp2-offload-01.yml",
  "base_model": "/home/user/gpt-oss-20b",
  "base_model_config": "/home/user/gpt-oss-20b",
  "batch_size": 4,
  "bf16": true,
  "capabilities": {
    "bf16": true,
    "compute_capability": "sm_120",
    "fp8": true,
    "n_gpu": 2,
    "n_node": 1,
    "tf32": true
  },
  "context_parallel_size": 1,
  "cut_cross_entropy": true,
  "dataloader_num_workers": 2,
  "dataloader_pin_memory": true,
  "dataloader_prefetch_factor": 256,
  "dataset_num_proc": 32,
  "dataset_prepared_path": "last_run_prepared",
  "datasets": [
    {
      "chat_template": "tokenizer_default",
      "field_thinking": "thinking",
      "message_property_mappings": {
        "content": "content",
        "role": "role"
      },
      "path": "reasoning_04.jsonl",
      "template_thinking_key": "thinking",
      "trust_remote_code": false,
      "type": "chat_template"
    }
  ],
  "ddp": true,
  "device": "cuda:0",
  "device_map": {
    "": 0
  },
  "dion_rank_fraction": 1.0,
  "dion_rank_multiple_of": 1,
  "eaft_alpha": 1.0,
  "eaft_k": 20,
  "env_capabilities": {
    "torch_version": "2.8.0"
  },
  "eot_tokens": [
    "<|end|>"
  ],
  "eval_batch_size": 1,
  "eval_causal_lm_metrics": [
    "sacrebleu",
    "comet",
    "ter",
    "chrf"
  ],
  "eval_max_new_tokens": 128,
  "eval_sample_packing": true,
  "eval_table_size": 0,
  "experimental_skip_move_to_device": true,
  "flash_attention": true,
  "fp16": false,
  "fsdp": true,
  "fsdp_config": {
    "auto_wrap_policy": "TRANSFORMER_BASED_WRAP",
    "fsdp_version": 2,
    "offload_params": true,
    "reshard_after_forward": true,
    "state_dict_type": "SHARDED_STATE_DICT",
    "transformer_layer_cls_to_wrap": "GptOssDecoderLayer"
  },
  "fsdp_version": 2,
  "generate_samples": false,
  "generation_do_sample": true,
  "generation_max_new_tokens": 50,
  "generation_prompt_ratio": 0.5,
  "generation_temperature": 0.7,
  "gradient_accumulation_steps": 2,
  "gradient_checkpointing": true,
  "gradient_checkpointing_kwargs": {
    "use_reentrant": true
  },
  "include_tkps": true,
  "layer_offloading": false,
  "learning_rate": 2e-05,
  "lisa_layers_attribute": "model.layers",
  "load_best_model_at_end": false,
  "load_in_4bit": false,
  "load_in_8bit": false,
  "local_rank": 0,
  "logging_steps": 1,
  "lora_dropout": 0.0,
  "loraplus_lr_embedding": 1e-06,
  "lr_scheduler": "constant_with_warmup",
  "mean_resizing_embeddings": false,
  "merge_method": "memory_efficient",
  "micro_batch_size": 1,
  "model_config_type": "gpt_oss",
  "model_quantization_config": "Mxfp4Config",
  "model_quantization_config_kwargs": {
    "dequantize": true
  },
  "num_epochs": 1.0,
  "num_generation_samples": 3,
  "optimizer": "adamw_torch_fused",
  "otel_metrics_host": "localhost",
  "otel_metrics_port": 8000,
  "output_dir": "./outputs/gpt-oss-20b-01/",
  "pad_to_sequence_len": true,
  "plugins": [
    "axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin"
  ],
  "pretrain_multipack_attn": true,
  "profiler_steps_start": 0,
  "qlora_sharded_model_loading": false,
  "quantize_moe_experts": false,
  "ray_num_workers": 1,
  "resources_per_worker": {
    "GPU": 1
  },
  "sample_packing": true,
  "sample_packing_bin_size": 200,
  "sample_packing_group_size": 100000,
  "save_only_model": false,
  "save_safetensors": true,
  "saves_per_epoch": 1,
  "sequence_len": 4096,
  "shuffle_before_merging_datasets": false,
  "shuffle_merged_datasets": true,
  "skip_prepare_dataset": false,
  "streaming_multipack_buffer_size": 10000,
  "strict": false,
  "tensor_parallel_size": 1,
  "tf32": true,
  "tiled_mlp_use_original_mlp": true,
  "tokenizer_config": "/home/user/gpt-oss-20b",
  "tokenizer_save_jinja_files": true,
  "torch_dtype": "torch.bfloat16",
  "train_on_inputs": false,
  "trl": {
    "async_prefetch": false,
    "log_completions": false,
    "mask_truncated_completions": false,
    "ref_model_mixup_alpha": 0.9,
    "ref_model_sync_steps": 64,
    "replay_buffer_size": 0,
    "replay_recompute_logps": true,
    "reroll_max_groups": 1,
    "reroll_start_fraction": 1.0,
    "reward_num_workers": 1,
    "scale_rewards": true,
    "skip_zero_advantage_batches": true,
    "sync_ref_model": false,
    "use_data_producer": false,
    "use_vllm": false,
    "vllm_lora_sync": false,
    "vllm_server_host": "0.0.0.0",
    "vllm_server_port": 8000
  },
  "use_kernels": true,
  "use_otel_metrics": false,
  "use_ray": false,
  "val_set_size": 0.0,
  "vllm": {
    "device": "auto",
    "dtype": "auto",
    "gpu_memory_utilization": 0.9,
    "host": "0.0.0.0",
    "port": 8000
  },
  "warmup_ratio": 0.03,
  "weight_decay": 0.0,
  "world_size": 2
}
[2026-04-03 07:48:28,026] [WARNING] [axolotl.cli.checks] Error verifying HuggingFace token. Remember to log in using `hf auth login` and get your access token from https://huggingface.co/settings/tokens if you want to use gated models or datasets.
[2026-04-03 07:48:29,544] [INFO] [axolotl.utils.data.shared] Loading prepared dataset from disk at last_run_prepared/740bf860ac7d0dabeadf609673c41970...
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1[Gloo] Rank 
1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[2026-04-03 07:48:33,698] [INFO] [axolotl.utils.samplers.multipack] gather_len_batches: [2865, 2865]
[2026-04-03 07:48:33,734] [INFO] [axolotl.utils.trainer] sample_packing_eff_est across ranks: [0.8389569520950317, 0.8386644124984741]
[2026-04-03 07:48:33,735] [INFO] [axolotl.utils.data.sft] Maximum number of steps set at 716
[2026-04-03 07:48:35,264] [INFO] [axolotl.loaders.patch_manager] Applying multipack dataloader patch for sample packing...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/cut_cross_entropy/__init__.py", line 76, in _check_requirements
[rank0]:     from cut_cross_entropy.transformers.patch import AXOLOTL_CCE_FORK
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/cut_cross_entropy/transformers/__init__.py", line 2, in <module>
[rank0]:     from cut_cross_entropy.transformers.patch import cce_patch
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/cut_cross_entropy/transformers/patch.py", line 16, in <module>
[rank0]:     from .gemma3 import patch_gemma2, patch_gemma3, patch_gemma3_text
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/cut_cross_entropy/transformers/gemma3.py", line 28, in <module>
[rank0]:     from transformers.cache_utils import Cache, HybridCache
[rank0]: ImportError: cannot import name 'HybridCache' from 'transformers.cache_utils' (/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/cache_utils.py)

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 124, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 91, in do_cli
[rank0]:     do_train(parsed_cfg, parsed_cli_args)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 45, in do_train
[rank0]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 582, in train
[rank0]:     ) = setup_model_and_trainer(cfg, dataset_meta)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 517, in setup_model_and_trainer
[rank0]:     model, tokenizer, peft_config, processor = setup_model_and_tokenizer(cfg)
[rank0]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 84, in setup_model_and_tokenizer
[rank0]:     model, peft_config = model_loader.load()
[rank0]:                          ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 173, in load
[rank0]:     PLUGIN_MANAGER.pre_model_load(self.cfg)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/base.py", line 446, in pre_model_load
[rank0]:     plugin.pre_model_load(cfg)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/cut_cross_entropy/__init__.py", line 89, in pre_model_load
[rank0]:     self._check_requirements()
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/cut_cross_entropy/__init__.py", line 81, in _check_requirements
[rank0]:     raise ImportError(
[rank0]: ImportError: Axolotl's fork of cut_cross_entropy is not installed. Please install Axolotl's fork of cut_cross_entropy with transformers support using `pip install "cut-cross-entropy[transformers] @ git+https://github.com/axolotl-ai-cloud/ml-cross-entropy.git@63b15e6"`
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/cut_cross_entropy/__init__.py", line 76, in _check_requirements
[rank1]:     from cut_cross_entropy.transformers.patch import AXOLOTL_CCE_FORK
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/cut_cross_entropy/transformers/__init__.py", line 2, in <module>
[rank1]:     from cut_cross_entropy.transformers.patch import cce_patch
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/cut_cross_entropy/transformers/patch.py", line 16, in <module>
[rank1]:     from .gemma3 import patch_gemma2, patch_gemma3, patch_gemma3_text
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/cut_cross_entropy/transformers/gemma3.py", line 28, in <module>
[rank1]:     from transformers.cache_utils import Cache, HybridCache
[rank1]: ImportError: cannot import name 'HybridCache' from 'transformers.cache_utils' (/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/cache_utils.py)

[rank1]: The above exception was the direct cause of the following exception:

[rank1]: Traceback (most recent call last):
[rank1]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank1]:   File "<frozen runpy>", line 88, in _run_code
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 124, in <module>
[rank1]:     fire.Fire(do_cli)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 91, in do_cli
[rank1]:     do_train(parsed_cfg, parsed_cli_args)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 45, in do_train
[rank1]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 582, in train
[rank1]:     ) = setup_model_and_trainer(cfg, dataset_meta)
[rank1]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 517, in setup_model_and_trainer
[rank1]:     model, tokenizer, peft_config, processor = setup_model_and_tokenizer(cfg)
[rank1]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 84, in setup_model_and_tokenizer
[rank1]:     model, peft_config = model_loader.load()
[rank1]:                          ^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 173, in load
[rank1]:     PLUGIN_MANAGER.pre_model_load(self.cfg)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/base.py", line 446, in pre_model_load
[rank1]:     plugin.pre_model_load(cfg)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/cut_cross_entropy/__init__.py", line 89, in pre_model_load
[rank1]:     self._check_requirements()
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/integrations/cut_cross_entropy/__init__.py", line 81, in _check_requirements
[rank1]:     raise ImportError(
[rank1]: ImportError: Axolotl's fork of cut_cross_entropy is not installed. Please install Axolotl's fork of cut_cross_entropy with transformers support using `pip install "cut-cross-entropy[transformers] @ git+https://github.com/axolotl-ai-cloud/ml-cross-entropy.git@63b15e6"`
[rank0]:[W403 07:48:36.562087922 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0403 07:48:37.519000 3113573 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3113936 closing signal SIGTERM
E0403 07:48:37.733000 3113573 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 3113935) of binary: /home/user/axolotl/venv/bin/python
Traceback (most recent call last):
  File "/home/user/axolotl/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1396, in launch_command
    multi_gpu_launcher(args)
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1023, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 143, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 277, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2026-04-03_07:48:37
  host      : mic
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3113935)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

I am on the latest Axolotl (0.16.1) and just tried reinstalling the cross cut entropy plugin to try again. Unfortunately the same issue appears.

**Comment by NanoCode012** [comment]
@floaty3 , hey, this means that the version of cut cross entropy you have isn't right. Sometimes it's because the current package exists, and it doesn't try to install the new one. 

Please run:
```bash
pip3 uninstall -y cut-cross-entropy && pip3 install "cut-cross-entropy[transformers] @ git+https://github.com/axolotl-ai-cloud/ml-cross-entropy.git@63b15e6"
```

Source; https://docs.axolotl.ai/docs/custom_integrations.html#installation

---

More context on error:

> Unfortunately, the custom CutCrossEntropyPlugin fails to import HybridCache:

Upstream's CCE hasn't really kept up with matching updates with transformers, so we've had to fork it and add patches ourselves.

**Comment by floaty3** [comment]
Thank you! I was following the error message's install instructions, and as you said, it was not installing a newer version. I think it would be helpful to update this message with the uninstall part: https://github.com/axolotl-ai-cloud/axolotl/blob/08fc7de87e79f38c367f6776c5111b40a914062e/src/axolotl/integrations/cut_cross_entropy/__init__.py#L36-L39

It now gets through loading the model weights, but then I am presented with another problem related to `CPUMegaBlocksMoeMLP`. This is the output after loading the model weights is finished:

```
Fetching ... files: 0it [00:00, ?it/s]
Fetching ... files: 68it [00:00, 342803.69it/s]
[rank1]: Traceback (most recent call last):
[rank1]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank1]:   File "<frozen runpy>", line 88, in _run_code
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 124, in <module>
[rank1]:     fire.Fire(do_cli)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 91, in do_cli
[rank1]:     do_train(parsed_cfg, parsed_cli_args)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 45, in do_train
[rank1]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 582, in train
[rank1]:     ) = setup_model_and_trainer(cfg, dataset_meta)
[rank1]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 517, in setup_model_and_trainer
[rank1]:     model, tokenizer, peft_config, processor = setup_model_and_tokenizer(cfg)
[rank1]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 84, in setup_model_and_tokenizer
[rank1]:     model, peft_config = model_loader.load()
[rank1]:                          ^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 176, in load
[rank1]:     skip_move_to_device = self._build_model()
[rank1]:                           ^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 830, in _build_model
[rank1]:     self.model = self._load_model_from_pretrained(model_loader_class)
[rank1]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 726, in _load_model_from_pretrained
[rank1]:     return loader.from_pretrained(self.base_model, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 387, in from_pretrained
[rank1]:     return model_class.from_pretrained(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4135, in from_pretrained
[rank1]:     model.set_use_kernels(use_kernels, kernel_config)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3676, in set_use_kernels
[rank1]:     self.use_kernels = True
[rank1]:     ^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2066, in __setattr__
[rank1]:     super().__setattr__(name, value)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4465, in use_kernels
[rank1]:     self.kernelize()
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4451, in kernelize
[rank1]:     kernelize(self, device=Device(type=self.device.type), mode=mode)
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/kernelize.py", line 268, in kernelize
[rank1]:     kernelize_layer(
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 360, in kernelize_layer
[rank1]:     layer = _get_layer_memoize(repo, module_class)
[rank1]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 507, in _get_layer_memoize
[rank1]:     layer = repo.load()
[rank1]:             ^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 91, in load
[rank1]:     return _get_kernel_layer(self, kernel)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 388, in _get_kernel_layer
[rank1]:     raise ValueError(f"Layer `{repo.layer_name}` not found in kernel repo {repo}.")
[rank1]: ValueError: Layer `CPUMegaBlocksMoeMLP` not found in kernel repo `kernels-community/megablocks` (revision: main), layer `CPUMegaBlocksMoeMLP`.

Fetching ... files: 0it [00:00, ?it/s]
Fetching ... files: 68it [00:00, 337529.79it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 124, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 91, in do_cli
[rank0]:     do_train(parsed_cfg, parsed_cli_args)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/cli/train.py", line 45, in do_train
[rank0]:     model, tokenizer, trainer = train(cfg=cfg, dataset_meta=dataset_meta)
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 582, in train
[rank0]:     ) = setup_model_and_trainer(cfg, dataset_meta)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 517, in setup_model_and_trainer
[rank0]:     model, tokenizer, peft_config, processor = setup_model_and_tokenizer(cfg)
[rank0]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/train.py", line 84, in setup_model_and_tokenizer
[rank0]:     model, peft_config = model_loader.load()
[rank0]:                          ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/telemetry/errors.py", line 124, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 176, in load
[rank0]:     skip_move_to_device = self._build_model()
[rank0]:                           ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 830, in _build_model
[rank0]:     self.model = self._load_model_from_pretrained(model_loader_class)
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/axolotl/loaders/model.py", line 726, in _load_model_from_pretrained
[rank0]:     return loader.from_pretrained(self.base_model, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 387, in from_pretrained
[rank0]:     return model_class.from_pretrained(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4135, in from_pretrained
[rank0]:     model.set_use_kernels(use_kernels, kernel_config)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3676, in set_use_kernels
[rank0]:     self.use_kernels = True
[rank0]:     ^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2066, in __setattr__
[rank0]:     super().__setattr__(name, value)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4465, in use_kernels
[rank0]:     self.kernelize()
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4451, in kernelize
[rank0]:     kernelize(self, device=Device(type=self.device.type), mode=mode)
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/kernelize.py", line 268, in kernelize
[rank0]:     kernelize_layer(
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 360, in kernelize_layer
[rank0]:     layer = _get_layer_memoize(repo, module_class)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 507, in _get_layer_memoize
[rank0]:     layer = repo.load()
[rank0]:             ^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 91, in load
[rank0]:     return _get_kernel_layer(self, kernel)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/axolotl/venv/lib/python3.12/site-packages/kernels/layer/layer.py", line 388, in _get_kernel_layer
[rank0]:     raise ValueError(f"Layer `{repo.layer_name}` not found in kernel repo {repo}.")
[rank0]: ValueError: Layer `CPUMegaBlocksMoeMLP` not found in kernel repo `kernels-community/megablocks` (revision: main), layer `CPUMegaBlocksMoeMLP`.
[rank0]:[W403 16:25:34.244485540 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0403 16:25:34.145000 3362858 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3363262 closing signal SIGTERM
E0403 16:25:34.509000 3362858 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 1 (pid: 3363263) of binary: /home/user/axolotl/venv/bin/python
Traceback (most recent call last):
  File "/home/user/axolotl/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1396, in launch_command
    multi_gpu_launcher(args)
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1023, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 143, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/axolotl/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 277, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2026-04-03_16:25:34
  host      : mic
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3363263)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by floaty3** [comment]
This isn't related to

```
[2026-04-03 16:21:09,374] [WARNING] [torchao] Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.8.0+cu128).
[2026-04-03 16:21:09,557] [WARNING] [torchao] Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.8.0+cu128).
```

is it?

**Comment by NanoCode012** [comment]
@floaty3 , nope, the latter torchao is just due to version incompatible.

> Thank you! I was following the error message's install instructions, and as you said, it was not installing a newer version. I think it would be helpful to update this message with the uninstall part:

Thanks for the feedback, will do, unless you're interested in making a PR? :)

> CPUMegablocks

Sorry, this took a while to get to, I noticed that this is only referenced once upstream https://github.com/huggingface/transformers/blob/b9f0fbf532c124ff836466d896a716e26dbe4722/src/transformers/integrations/hub_kernels.py#L162-L166

So, like mentioned on discord, are you sure there's no Nvidia cuda installation / pytorch incompatibility issues? Does `nvidia-smi` `nvcc -V` all work? Does the below run as expected?

```python
>>> import torch

>>> torch.cuda.is_available()
True

>>> torch.cuda.device_count()
1

```

**Comment by ved1beta** [comment]
the issue was due to no mxfp4 support in bnb , gpt oos ships native mxfp4 
we have mxfp4 kernal suppport for MoEs https://github.com/axolotl-ai-cloud/axolotl/pull/3663 NOW ! 
you could try this config 
```
base_model: openai/gpt-oss-20b
use_kernels: true
use_scattermoe: true
experts_implementation: scattermoe
model_quantization_config: Mxfp4Config
model_quantization_config_kwargs:
  dequantize: false  # keep experts in MXFP4; ScatterMoE selectively dequantizes active experts

plugins:
  - axolotl.integrations.kernels.KernelsPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin

experimental_skip_move_to_device: true  # prevent OOM by not putting model to GPU before sharding

datasets:
  - path: HuggingFaceH4/Multilingual-Thinking
    type: chat_template
    field_thinking: thinking
    template_thinking_key: thinking

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./outputs/gpt-oss-out/

sequence_len: 4096
sample_packing: true

adapter: lora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.0  # must be 0 with lora_target_parameters
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
lora_target_parameters:  # expert LoRA on the MXFP4 3D expert tensors
  - experts.gate_up_proj
  - experts.down_proj
lora_mlp_kernel: false
lora_qkv_kernel: false
lora_o_kernel: false

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

trackio_project_name:
trackio_run_name:
trackio_space_id:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1

optimizer: adamw_torch_8bit
lr_scheduler: constant_with_warmup
learning_rate: 2e-4

bf16: true
tf32: true

attn_implementation: kernels-community/vllm-flash-attn3  # this is not needed if using flash_attn >= 2.8.3

gradient_checkpointing: true
activation_offloading: true

logging_steps: 1
saves_per_epoch: 1
warmup_ratio: 0.1

special_tokens:
eot_tokens:
  - "<|end|>"
```
