### ISSUE TITLE
flash_attn_2_cuda error

### ISSUE THREAD

**Issue by manishiitg** [axolotl-ai-cloud/axolotl#674]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

should work

### Current behaviour

  File "/opt/conda/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):

### Steps to reproduce

install repo from master and run fine tuning script

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.9

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by manishiitg** [comment]
this happens mainly when fine tuning mistral model

**Comment by NanoCode012** [comment]
Hi, may I ask if you've installed flash attention following the instructions on readme?

Does this error happen for llama FA?

**Comment by l3utterfly** [comment]
I just got this error. The solution for me is to compile flash attention from source. Follow the compile from source instruction in the flash_attention repo

Not sure why the axolotl install script doesn't compile flash attention from source, it just seems to pull a version from somewhere which uses cuda 12.

**Comment by NanoCode012** [comment]
@l3utterfly , currently, we install from pip which FA devs built and pushed. It could be an issue upstream?

**Comment by l3utterfly** [comment]
Could be. I suspect they published flash attention 2 which only supports CUDA 12.x. This project seems to only support CUDA 11.x

I tried updating CUDA, but it needs transformers 2.1, this project references 2.0.1
________________________________

**Comment by NanoCode012** [comment]
Seems like their workflow does include 11.x . It has worked so far for us, unless they recently changed something.

https://github.com/Dao-AILab/flash-attention/blob/5e525a8dc8a473f418c8aaf82f5322eb225d9ee5/.github/workflows/publish.yml#L48

**Comment by manishiitg** [comment]
when compiling axolotl from source as per readme. i get this pip error  as well

```
torchvision 0.16.0 requires torch==2.1.0, but you have torch 2.0.1 which is incompatible.
```

**Comment by manishiitg** [comment]
was able to get this run after upgrading to cuda12.2 and installing flash attention from source.

but i am still not able to fine tune mistral model. 
keep getting this error 

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.00 GiB. GPU 0 has a total capacty of 39.39 GiB of which 1020.88 MiB is free. Including non-PyTorch memory, this process has 38.38 GiB memory in use. Of the allocated memory 25.79 GiB is allocated by PyTorch, and 12.09 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

i have reduced micro_batch_size to 1, previously i was able to run on micro_batch_size: 8

i am using single A100 gpu

**Comment by manishiitg** [comment]
possible to enable flash attention 1 till this is fixed?

**Comment by l3utterfly** [comment]
Try using deep speed zero2 or zero3.

I got it to fine tune on a Rtx5000 (24GB vram) with this setup
________________________________

**Comment by NanoCode012** [comment]
@manishiitg , can you try with `sample_packing: true`?

> possible to enable flash attention 1 till this is fixed?

Sorry, this has been deprecated a while back. If the above does not work, could you try downgrade FA a few minor versions?

**Comment by manishiitg** [comment]
``` sample_packing: true ``` is already enabled. will try by lowering version of FA

**Comment by manishiitg** [comment]
didn't work even after lowering FA version

**Comment by NanoCode012** [comment]
@manishiitg , are you able to use docker? I just ran the below in docker and it works.

```bash
accelerate launch -m axolotl.cli.train examples/mistral/qlora.yml
```

**Comment by manishiitg** [comment]
let me try with docker.

also just an FYI i am using spot instances for A100 started via skypilot. i suspect that might be an issue? 

but the same used to work well before FA2

**Comment by NanoCode012** [comment]
> but the same used to work well before FA2

Do you mean with FA1 with axolotl?

>  A100 started via skypilot. i suspect that might be an issue?

Unfortunately, I have not used that tool before.

**Comment by manishiitg** [comment]
yes correction. FA1 with axolotl

**Comment by manishiitg** [comment]
works well with docker

**Comment by NanoCode012** [comment]
@manishiitg , seems it's an environment issue then..

**Comment by manishiitg** [comment]
got it. thanks.

will figure out an alternate

**Comment by generalsvr** [comment]
Same here. Latest docker image, tried to install from source. Yesterday worked well, today not. Fine-tuning llama2 13b, no deepspeed

**Comment by generalsvr** [comment]
How can I find docker images of axolotl other than main?
